import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {database} from './database.mjs';
import {emptyData,applyOperations} from '../lib/domain.ts';
import {fingerprint} from '../lib/fingerprint.ts';
import {captureBaseline,mergeChanges,stable} from '../lib/changes.ts';
import {loadWorkspace,readOperation,settleOperation,metadata} from '../lib/workspace-storage.ts';
import {commitWorkspace,commitChat,chatHistory,chatUpdates,dismissProposal,readChatReceipt} from '../lib/chat-state.ts';
import {commitRestore} from '../lib/restore-state.ts';
import {acknowledgeDraft,rebaseSubmittedOperations} from '../lib/editor-draft.ts';
import {visibleTaskPosition} from '../lib/planning.ts';
const project={id:'p',name:'项目',start:'2026-09-01',end:'2026-09-30'};
function fixture(count=60){let d=applyOperations(emptyData(),[{type:'project.save',data:project}],'seed');for(let i=0;i<count;i++)d=applyOperations(d,[{type:'task.save',data:{id:'t'+i,projectId:'p',name:'事项'+i,start:'2026-09-01',end:'2026-09-20',description:'文'.repeat(7000)}}],'task-'+i);return d;}

test('SHA-256 UTF-8指纹与标准实现一致，包括分块边界和百万字符',()=>{for(const value of ['', 'abc', 'a'.repeat(55),'a'.repeat(56),'a'.repeat(64),'安排😀'.repeat(2000),'a'.repeat(1000000)])assert.equal(fingerprint(value),createHash('sha256').update(value).digest('hex'));});
test('确认丢失响应时只重放上次提交后的用户新改动，不回滚已合并的远端字段',()=>{
 const previous=[{type:'project.save',data:{...project,name:'第一次',goal:'旧目标'}}],wanted=[{type:'project.save',data:{...project,name:'第二次',goal:'旧目标'}}];
 const receipt={status:'applied',records:[{kind:'project',id:'p',value:{...project,name:'第一次',goal:'另一设备的新目标'}}]};
 const rebased=rebaseSubmittedOperations(previous,wanted,receipt);assert.equal(rebased[0].data.name,'第二次');assert.equal(rebased[0].data.goal,'另一设备的新目标');
 const mine=rebaseSubmittedOperations(previous,[{type:'project.save',data:{...wanted[0].data,goal:'本次明确修改目标'}}],receipt);assert.equal(mine[0].data.goal,'本次明确修改目标');
});
test('大项目删除请求保持短小，任何新增子项仍阻止旧删除',()=>{const data=fixture(),ops=[{type:'project.delete',id:'p'}],base=captureBaseline(data,ops);assert.ok(Buffer.byteLength(JSON.stringify({ops,base}))<1000);assert.equal(mergeChanges(data,ops,base).length,1);const changed=applyOperations(data,[{type:'task.save',data:{...data.tasks[0],description:'其他设备新内容'}}],'new');assert.throws(()=>mergeChanges(changed,ops,base),/新的修改/);});
test('旧工作空间无损原子迁移、重复迁移无副作用，禁止旧worker写回整包',async()=>{const {sql,db,snapshot}=database(),legacy=fixture(3);legacy.messages=[{id:'m',role:'user',content:'旧消息',at:'now'}];sql.prepare('UPDATE workspaces SET storage_version=0,payload=? WHERE owner=?').run(JSON.stringify(legacy),'owner');const migrated=await loadWorkspace(db,'owner');assert.deepEqual(migrated.data,legacy);assert.deepEqual((await loadWorkspace(db,'owner')).data,legacy);assert.equal(sql.prepare('SELECT count(*) n FROM workspace_records').get().n,9);assert.throws(()=>sql.prepare('UPDATE workspaces SET payload=? WHERE owner=?').run(JSON.stringify(legacy),'owner'),/upgrade required/);assert.deepEqual(snapshot().data,legacy);sql.close();});
test('迁移中途失败保留旧数据，清除故障后可完整重试',async()=>{const {sql,db}=database(),data=fixture(2);sql.prepare('UPDATE workspaces SET storage_version=0,payload=? WHERE owner=?').run(JSON.stringify(data),'owner');sql.exec("CREATE TRIGGER migration_fault BEFORE INSERT ON workspace_records WHEN NEW.kind='tasks' BEGIN SELECT RAISE(ABORT,'migration fault'); END");await assert.rejects(loadWorkspace(db,'owner'),/migration fault/);assert.equal(sql.prepare('SELECT storage_version FROM workspaces').get().storage_version,0);assert.equal(sql.prepare('SELECT count(*) n FROM workspace_records').get().n,0);sql.exec('DROP TRIGGER migration_fault');assert.deepEqual((await loadWorkspace(db,'owner')).data,data);sql.close();});
test('超过2MB工作空间可原子恢复、读取、编辑、聊天、删除，无整包行',async()=>{const {sql,db,snapshot,batches}=database(),large=fixture(110);assert.ok(Buffer.byteLength(JSON.stringify(large))>2000000);assert.equal(await commitRestore(db,'owner',snapshot(),large,'large-restore','hash'),true);assert.deepEqual(snapshot().data,large);let current=snapshot(),next=applyOperations(current.data,[{type:'task.save',data:{id:'t0',result:'真实推进'}}],'edit');assert.equal(await commitWorkspace(db,'owner',current,next,'edit','hash'),true);await commitChat(db,'owner',snapshot(),'large-chat','你好','你好',null,large.workRevision);assert.equal(snapshot().data.tasks.length,110);current=snapshot();next=applyOperations(current.data,[{type:'project.delete',id:'p'}],'delete');assert.equal(await commitWorkspace(db,'owner',current,next,'delete'),true);assert.equal(snapshot().data.tasks.length,0);assert.equal(snapshot().data.messages.length,2);assert.ok(Math.max(...batches)<50);assert.ok(sql.prepare('SELECT max(length(CAST(payload AS BLOB))) bytes FROM workspace_records').get().bytes<2000000);sql.close();});
test('不同token竞争只允许一个提交，中途失败整批回滚包括回执',async()=>{const {sql,db,snapshot}=database(),before=snapshot(),data=applyOperations(before.data,[{type:'project.save',data:project}],'one');assert.equal(await commitWorkspace(db,'owner',before,data,'one'),true);assert.equal(await commitWorkspace(db,'owner',before,data,'two'),false);assert.equal(await readOperation(db,'owner','two'),null);sql.exec("CREATE TRIGGER record_fault BEFORE INSERT ON workspace_records BEGIN SELECT RAISE(ABORT,'record fault'); END");const latest=snapshot(),changed=applyOperations(latest.data,[{type:'project.save',data:{id:'p',name:'修改'}}],'three');await assert.rejects(commitWorkspace(db,'owner',latest,changed,'three'),/record fault/);assert.deepEqual(snapshot(),latest);assert.equal(await readOperation(db,'owner','three'),null);sql.close();});
test('持久回执超过100次后仍幂等；取消栅栏阻止旧请求迟到落盘',async()=>{const {sql,db,snapshot}=database();let old;for(let i=0;i<105;i++){const before=snapshot(),data=applyOperations(before.data,[{type:'project.save',data:{...project,name:'项目'+i}}],'operation-'+i);if(!i)old={before,data};assert.equal(await commitWorkspace(db,'owner',before,data,'operation-'+i,'hash'+i),true);}assert.ok(!snapshot().data.appliedIds.includes('operation-0'));assert.equal((await readOperation(db,'owner','operation-0')).fingerprint,'hash0');assert.equal(await commitWorkspace(db,'owner',snapshot(),old.data,'operation-0','hash0'),false);const revision=snapshot().revision;assert.equal((await settleOperation(db,'owner','uncertain','intent')).status,'cancelled');assert.equal(await commitWorkspace(db,'owner',snapshot(),old.data,'uncertain','intent'),false);assert.equal(snapshot().revision,revision);assert.equal(await readOperation(db,'other','operation-0'),null);sql.close();});
test('丢失响应后改稿以提交回执重设基线，仍保护另一设备的新字段',async()=>{const {sql,db,snapshot}=database(),ops=[{type:'project.save',data:project}],baseline=captureBaseline(snapshot().data,ops),draft={version:1,kind:'project',id:'p',record:null,baseline,deletionBaseline:{records:[],deletions:{}},entries:[['name','本次继续修改']],attempt:{id:'lost',fingerprint:JSON.stringify(ops)}};const saved=applyOperations(snapshot().data,ops,'lost');await commitWorkspace(db,'owner',snapshot(),saved,'lost','hash');const remote=applyOperations(snapshot().data,[{type:'project.save',data:{id:'p',goal:'另一设备补充目标'}}],'remote');await commitWorkspace(db,'owner',snapshot(),remote,'remote','hash2');const receipt=await settleOperation(db,'owner','lost','hash'),recovered=acknowledgeDraft(draft,receipt,snapshot().data);assert.deepEqual(recovered.entries,draft.entries);assert.equal(recovered.record.goal,'');const merged=mergeChanges(snapshot().data,[{type:'project.save',data:{...saved.projects[0],name:'本次继续修改'}}],recovered.baseline);assert.equal(merged[0].data.goal,'另一设备补充目标');assert.equal(merged[0].data.name,'本次继续修改');assert.equal(snapshot().data.projects.length,1);sql.close();});
test('离线200轮对话按提交序号全部补齐，时钟回拨和业务版本间隙不漏消息',async()=>{const {sql,db,snapshot}=database();const initial=await chatHistory(db,'owner');for(let i=0;i<200;i++)await commitChat(db,'owner',snapshot(),'sync-'+String(i).padStart(3,'0'),'问题'+i,'回答'+i,null,0);sql.exec("UPDATE chat_receipts SET created_at='2020-01-01T00:00:00Z'");let cursor=initial.watermark,until=snapshot().revision,messages=[];do{const page=await chatUpdates(db,'owner',cursor,until);messages.push(...page.messages);cursor=page.nextAfter;}while(cursor<until);assert.equal(messages.length,400);assert.equal(new Set(messages.map(m=>m.id)).size,400);assert.equal((await chatUpdates(db,'other',0,until)).messages.length,0);const current=snapshot();await commitWorkspace(db,'owner',current,applyOperations(current.data,[{type:'project.save',data:project}],'business'),'business');const gap=await chatUpdates(db,'owner',cursor);assert.equal(gap.nextAfter,snapshot().revision);assert.equal(gap.messages.length,0);sql.close();});
test('放弃方案与revision同事务提交，应用竞争失败且业务版本不误增',async()=>{const {sql,db,snapshot}=database(),plan={summary:'新项目',operations:[{type:'project.save',data:project}]};await commitChat(db,'owner',snapshot(),'proposal-test','安排','方案',plan,0,captureBaseline(snapshot().data,plan.operations));const stale=snapshot();assert.equal(await dismissProposal(db,'owner',stale,'proposal-test'),true);assert.equal(snapshot().revision,stale.revision+1);assert.equal(snapshot().data.workRevision,stale.data.workRevision);assert.equal(await commitWorkspace(db,'owner',stale,applyOperations(stale.data,plan.operations,'proposal-test-apply'),'proposal-test-apply'),false);assert.equal((await readChatReceipt(db,'owner','proposal-test')).proposal_state,'dismissed');assert.equal(await dismissProposal(db,'owner',snapshot(),'proposal-test'),false);sql.close();});
test('大型方案正文及基线分行存储，回读恢复完整计划',async()=>{const {sql,db,snapshot,update}=database();const data=emptyData();data.projects=Array.from({length:100},(_,i)=>({...project,id:'p'+i,goal:'',status:'active',color:'green'}));data.contacts=Array.from({length:30},(_,i)=>({id:'c'+i,name:'联系人'+i,wechat:'',notes:'文'.repeat(8000),roles:data.projects.map(p=>({projectId:p.id,role:'职'.repeat(300)}))}));update(data);const plan={summary:'更新职责',operations:data.contacts.map(c=>({type:'contact.save',data:{...c,wechat:'new'}}))},baseline=captureBaseline(snapshot().data,plan.operations);assert.ok(Buffer.byteLength(JSON.stringify({plan,baseline}))>2000000);await commitChat(db,'owner',snapshot(),'huge-plan','更新','方案',plan,0,baseline);const receipt=await readChatReceipt(db,'owner','huge-plan');assert.deepEqual(JSON.parse(receipt.proposal),plan);assert.deepEqual(JSON.parse(receipt.base_records),baseline);assert.ok(sql.prepare('SELECT length(CAST(proposal AS BLOB))+length(CAST(base_records AS BLOB)) bytes FROM chat_receipts').get().bytes<1000);sql.close();});
test('时间条裁剪后保留可见名称空间，标记前后延续，不渲染完全窗外任务',()=>{const task={start:'2026-09-12',end:'2026-09-19'};const a=visibleTaskPosition('2026-09-14',task,100,14);assert.equal(a.left,0);assert.equal(a.before,true);assert.equal(a.width,597);const b=visibleTaskPosition('2026-09-14',task,100,14,200,300);assert.deepEqual(b,{left:200,width:300,before:true,after:true});assert.equal(visibleTaskPosition('2026-10-01',task,100,14).width,0);});

