'use client';
import {useEffect,useRef,useState} from 'react';
import {recordingToWav} from '@/lib/audio';
import {ArrowUp,AudioLines,Mic,Square,Volume2,X,Sparkles,Check,Loader2,ChevronDown} from 'lucide-react';
import {type Snapshot,type Operation,type Data,collisions,type Block} from '@/lib/domain';
export type Draft={summary:string;operations:Operation[];revision:number;id:string};
type Props={snapshot:Snapshot;receive:(s:Snapshot)=>void;save:(ops:Operation[],summary:string,revision?:number,id?:string)=>Promise<boolean>;close:()=>void;globalBusy:boolean};
async function jsonFetch(url:string,body:unknown,signal?:AbortSignal){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'请求未完成');return j;}
export function operationLabel(op:Operation,data:Data){const kind=op.type.split('.')[0];const list=kind==='project'?data.projects:kind==='task'?data.tasks:kind==='block'?data.blocks:kind==='contact'?data.contacts:data.resources;const value=op.data as any;const prev=list.find(v=>v.id===(op.id||value?.id));return {verb:op.type.endsWith('.delete')?'删除':prev?'更新':'新增',name:value?.name||prev?.name||op.id||'记录',value};}
function ChangeDetails({operation,snapshot}:{operation:Operation;snapshot:Snapshot}){const labels:Record<string,string>={name:'名称',shortName:'条内简称',goal:'目标',description:'具体内容',start:'开始',end:'结束',owner:'负责人',hours:'预计投入小时',result:'推进成果',device:'所在电脑',path:'文件夹路径',purpose:'目录用途',wechat:'联系方式',notes:'备注',fixed:'固定日程',done:'日程完成',projectId:'所属项目',taskId:'关联事项',contactId:'联系人',dependencies:'前置事项',roles:'项目角色'};const d=snapshot.data;return <dl>{Object.entries((operation.data||{}) as Record<string,unknown>).filter(([key])=>labels[key]).map(([key,value])=>{let display=String(value||'未填写');if(typeof value==='boolean')display=value?'是':'否';if(key==='hours')display=String(value);if(key==='projectId')display=d.projects.find(p=>p.id===value)?.name||'本次方案中的新项目';if(key==='taskId')display=d.tasks.find(t=>t.id===value)?.name||(value?'本次方案中的新事项':'独立日程');if(key==='contactId')display=d.contacts.find(c=>c.id===value)?.name||(value?'本次方案中的新联系人':'无');if(key==='dependencies')display=(value as string[]).map(id=>d.tasks.find(t=>t.id===id)?.name||'本次方案中的新事项').join('、')||'无';if(key==='roles')display=(value as {projectId:string;role:string}[]).map(r=>(d.projects.find(p=>p.id===r.projectId)?.name||'新项目')+'：'+r.role).join('；')||'无';return <div key={key}><dt>{labels[key]}</dt><dd>{display}</dd></div>})}{operation.type.endsWith('.delete')&&<dd>删除此记录并解除相关关联；已完成日程会保留。</dd>}</dl>}
export default function Assistant({snapshot,receive,save,close,globalBusy}:Props){
 const [text,setText]=useState(''),[config,setConfig]=useState<boolean|null>(null),[localTest,setLocalTest]=useState(false),[phase,setPhase]=useState<'idle'|'permission'|'recording'|'recognizing'|'chatting'>('idle'),[error,setError]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[seconds,setSeconds]=useState(0),[speak,setSpeak]=useState(false),[speaking,setSpeaking]=useState(false),[pending,setPending]=useState(''),[audioBusy,setAudioBusy]=useState(false);
 const mounted=useRef(true);const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),token=useRef(0),abort=useRef<AbortController|null>(null),audio=useRef<HTMLAudioElement|null>(null),audioUrl=useRef(''),audioToken=useRef(0),audioAbort=useRef<AbortController|null>(null),list=useRef<HTMLDivElement>(null);
 useEffect(()=>{mounted.current=true;fetch('/api/qwen/status').then(r=>r.json()).then((c:any)=>{setConfig(!!c.configured);setLocalTest(!!c.localTest)}).catch(()=>setConfig(false));return()=>{mounted.current=false;token.current++;abort.current?.abort();if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());audioToken.current++;audioAbort.current?.abort();audio.current?.pause();if(audioUrl.current)URL.revokeObjectURL(audioUrl.current)}},[]);
 useEffect(()=>{list.current?.scrollTo({top:list.current.scrollHeight,behavior:'smooth'})},[snapshot.data.messages.length,draft,pending]);
 const ready=phase==='idle'&&!globalBusy;
 function stopAudio(){audioToken.current++;audioAbort.current?.abort();audio.current?.pause();if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current='';setSpeaking(false);setAudioBusy(false);}
 async function read(text:string){stopAudio();const current=audioToken.current,controller=new AbortController();audioAbort.current=controller;setAudioBusy(true);setError('');try{const r=await fetch('/api/qwen/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,580)}),signal:controller.signal});if(!r.ok)throw new Error(((await r.json()) as {error?:string}).error||'语音生成失败');const blob=await r.blob();if(current!==audioToken.current)return;audioUrl.current=URL.createObjectURL(blob);const a=new Audio(audioUrl.current);audio.current=a;a.onended=()=>{setSpeaking(false);URL.revokeObjectURL(audioUrl.current);audioUrl.current=''};await a.play();setSpeaking(true)}catch(e){if(current===audioToken.current)setError(e instanceof Error?e.message:'暂时无法播放语音')}finally{if(current===audioToken.current)setAudioBusy(false)}}
 async function send(){if(!text.trim()||!ready)return;const value=text.trim();setError('');setPhase('chatting');setPending(value);stopAudio();try{const r=await jsonFetch('/api/qwen/chat',{text:value,revision:snapshot.revision,requestId:crypto.randomUUID()});receive(r.snapshot);if(!mounted.current)return;setDraft(r.draft);setText('');if(speak)void read(r.reply)}catch(e){setError(e instanceof Error?e.message:'对话失败，请重试。')}finally{if(mounted.current){setPhase('idle');setPending('')}}}
 function cancel(){token.current++;abort.current?.abort();if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setPhase('idle');setSeconds(0);}
 function finish(){if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());}
 async function record(){if(!ready)return;setError('');stopAudio();if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('当前浏览器不支持录音，请使用新版 Chrome / Edge，或直接输入。');return}const current=++token.current;setPhase('permission');try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(current!==token.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));const rec=new MediaRecorder(s,mime?{mimeType:mime}:undefined);recorder.current=rec;const chunks:Blob[]=[];let bytes=0;rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>5500000)finish()}};rec.onerror=()=>{cancel();setError('录音被中断，请重新录制。')};rec.onstop=async()=>{s.getTracks().forEach(t=>t.stop());if(current!==token.current)return;setPhase('recognizing');const blob=new Blob(chunks,{type:rec.mimeType.split(';')[0]||'audio/webm'});if(blob.size<500){setError('录音太短，请再说一次。');setPhase('idle');return}try{const wav=await recordingToWav(blob);const base64=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=reject;f.readAsDataURL(wav)});if(current!==token.current)return;const controller=new AbortController();abort.current=controller;const r=await jsonFetch('/api/qwen/asr',{audio:base64},controller.signal);if(current===token.current){setText(t=>t?t+'\n'+r.text:r.text);setError('')}}catch(e){if(current===token.current)setError(e instanceof Error?e.message:'识别失败，请重试。')}finally{if(current===token.current)setPhase('idle')}};rec.start(250);setSeconds(0);setPhase('recording');let elapsed=0;timer.current=setInterval(()=>{elapsed++;setSeconds(elapsed);if(elapsed>=60)finish()},1000)}catch(e){if(current===token.current){cancel();setError(e instanceof DOMException&&e.name==='NotAllowedError'?'麦克风权限未开启。可以在浏览器地址栏授权，或直接输入。':'无法启用麦克风，请检查设备后重试。')}}}
 async function apply(){if(!draft)return;const overlap=draft.operations.filter(o=>o.type==='block.save').flatMap(o=>collisions(snapshot.data,o.data as Block));if(overlap.length&&!window.confirm('方案中的日程与现有安排有重叠，请检查时间。仍要应用吗？'))return;const deleting=draft.operations.some(o=>o.type.endsWith('.delete'));if(deleting&&!window.confirm('方案包含删除操作。请确认已经核对下方记录；删除会同步解除相关关联。'))return;if(await save(draft.operations,draft.summary,draft.revision,draft.id))setDraft(null);}
 return <aside className="assistant-panel"><div className="assistant-header"><div className="row"><div className="assistant-symbol"><AudioLines size={19}/></div><div><strong>时间伙伴</strong><span><i className={config?'online-dot':'offline-dot'}/>{config?(localTest?'Qwen · 本机测试':'Qwen 已配置'):config===null?'检查连接…':'等待配置 Qwen'}</span></div></div><button onClick={close} className="icon-button" aria-label="收起时间伙伴"><X size={17}/></button></div><div className="assistant-intro"><span className="eyebrow">THINK OUT LOUD</span><h2>把脑中的事，<br/>慢慢理清楚。</h2><p>聊聊近况，安排下一步。<br/>你的项目、日程和上下文都在这里。</p></div><div className="chat-scroll" ref={list}>
 {!snapshot.data.messages.length&&<div className="starter-prompts"><small>可以从这里开始</small>{['看看我目前哪些项目需要推进','今天有什么可以优先做的？','帮我为一个事项安排专注时间'].map(s=><button key={s} onClick={()=>setText(s)}>{s}<ArrowUp size={13}/></button>)}</div>}
 {snapshot.data.messages.map(m=><div key={m.id} className={'message '+m.role}><small>{m.role==='user'?'你':'时间伙伴'}</small><p>{m.content}</p>{m.role==='assistant'&&<button className="read-button" disabled={!config||audioBusy} onClick={()=>read(m.content)}><Volume2 size={13}/>朗读</button>}</div>)}
 {pending&&<><div className="message user"><small>你</small><p>{pending}</p></div><div className="thinking"><Loader2 size={14} className="spin"/>正在梳理你的安排…</div></>}
 {draft&&<div className="draft-card"><div className="row"><Sparkles size={15}/><strong>待应用的安排</strong></div><p>{draft.summary}</p>{draft.operations.map((o,i)=>{const l=operationLabel(o,snapshot.data);return <div className="draft-item" key={i}><span className={l.verb==='删除'?'danger-text':''}>{l.verb} · {l.name}</span>{l.value?.start&&<small>{l.value.start.replace('T',' ')} → {l.value.end?.replace('T',' ')}</small>}{l.value?.status&&<small>状态：{({active:'推进中',paused:'暂停',done:'已完成',doing:'进行中',waiting:'等待',todo:'待开始'} as any)[l.value.status]}</small>}<details><summary>查看完整变更 <ChevronDown size={11}/></summary><ChangeDetails operation={o} snapshot={snapshot}/></details></div>})}{draft.revision!==snapshot.revision?<p className="form-error">工作空间已改变，此方案已失效。请让助理重新安排。</p>:<button className="primary full" disabled={!ready} onClick={apply}><Check size={15}/>应用 {draft.operations.length} 项安排</button>}<button className="text-button full" disabled={!ready} onClick={()=>setDraft(null)}>放弃这次方案</button></div>}
 </div><div className="composer"><div className="voice-preference"><label><input type="checkbox" checked={speak} onChange={e=>setSpeak(e.target.checked)}/>语音回复</label>{(speaking||audioBusy)&&<button className="text-button" onClick={stopAudio}><Square size={11}/>{audioBusy?'取消生成':'停止朗读'}</button>}</div>{error&&<div className="assistant-error" role="alert">{error}</div>}{!config&&<p className="setup-note">Qwen 尚未连接。项目和日程可正常使用。</p>}
 <div className={'input-box '+(phase==='recording'?'recording':'')}><textarea aria-label="和时间伙伴聊天" value={text} onChange={e=>setText(e.target.value)} placeholder={phase==='recording'?'正在听你说…':'说说你想安排的事…'} maxLength={8000} disabled={phase==='chatting'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><div className="composer-actions">{phase==='recording'?<button onClick={finish} className="record-stop"><Square size={14}/>说完了 · {seconds}s</button>:phase==='permission'||phase==='recognizing'?<span className="small muted"><Loader2 size={14} className="spin"/>{phase==='permission'?'等待麦克风权限…':'Qwen 正在识别…'}</span>:<button className="mic-button" disabled={!ready||!config} onClick={record} aria-label="开始 Qwen 语音输入"><Mic size={18}/><span>语音输入</span></button>}{['permission','recording','recognizing'].includes(phase)?<button className="text-button" onClick={cancel}>取消</button>:<button className="send-button" aria-label="发送消息" disabled={!text.trim()||!ready||!config} onClick={send}>{phase==='chatting'?<Loader2 className="spin" size={17}/>:<ArrowUp size={18}/>}</button>}</div></div><p className="composer-hint">识别后可编辑文字 · Enter 发送 · 修改经你确认后生效</p></div></aside>;
}
