'use client';
import {useConfirmation} from './confirmation';
import {useEffect,useRef,useState,type MutableRefObject} from 'react';
import {type SaveWorkspace} from './use-workspace';
import {speechChunks} from '@/lib/speech';
import {mergeChanges} from '@/lib/changes';
import {changeWarnings} from '@/lib/planning';
import {type Draft} from '@/lib/chat-state';
import {recordingToWav} from '@/lib/audio';
import {requestJson,requestAudio,ClientError,errorMessage} from '@/lib/api-client';
import {ArrowUp,AudioLines,Mic,Square,Volume2,X,Sparkles,Check,Loader2,ChevronDown} from 'lucide-react';
import {type Snapshot,type Operation,type Data,collisions,type Block} from '@/lib/domain';

type Props={snapshot:Snapshot;receive:(s:Snapshot)=>void;save:SaveWorkspace;close:()=>void;visible:boolean;closeRequest:MutableRefObject<()=>void>;globalBusy:boolean};
export function operationLabel(op:Operation,data:Data){const kind=op.type.split('.')[0];const list=kind==='project'?data.projects:kind==='task'?data.tasks:kind==='block'?data.blocks:kind==='contact'?data.contacts:data.resources;const value=op.data as any;const prev=list.find(v=>v.id===(op.id||value?.id));return {verb:op.type.endsWith('.delete')?'删除':prev?'更新':'新增',name:value?.name||prev?.name||op.id||'记录',value};}
function ChangeDetails({operation,snapshot}:{operation:Operation;snapshot:Snapshot}){const labels:Record<string,string>={name:'名称',shortName:'条内简称',goal:'目标',description:'具体内容',start:'开始',end:'结束',owner:'负责人',hours:'预计投入小时',result:'推进成果',device:'所在电脑',path:'文件夹路径',purpose:'目录用途',wechat:'联系方式',notes:'备注',fixed:'固定日程',done:'日程完成',projectId:'所属项目',taskId:'关联事项',contactId:'联系人',dependencies:'前置事项',roles:'项目角色'};const d=snapshot.data;return <dl>{Object.entries((operation.data||{}) as Record<string,unknown>).filter(([key])=>labels[key]).map(([key,value])=>{let display=String(value||'未填写');if(typeof value==='boolean')display=value?'是':'否';if(key==='hours')display=String(value);if(key==='projectId')display=d.projects.find(p=>p.id===value)?.name||'本次方案中的新项目';if(key==='taskId')display=d.tasks.find(t=>t.id===value)?.name||(value?'本次方案中的新事项':'独立日程');if(key==='contactId')display=d.contacts.find(c=>c.id===value)?.name||(value?'本次方案中的新联系人':'无');if(key==='dependencies')display=(value as string[]).map(id=>d.tasks.find(t=>t.id===id)?.name||'本次方案中的新事项').join('、')||'无';if(key==='roles')display=(value as {projectId:string;role:string}[]).map(r=>(d.projects.find(p=>p.id===r.projectId)?.name||'新项目')+'：'+r.role).join('；')||'无';return <div key={key}><dt>{labels[key]}</dt><dd>{display}</dd></div>})}{operation.type.endsWith('.delete')&&<dd>删除此记录并解除相关关联；已完成日程会保留。</dd>}</dl>}
export default function Assistant({snapshot,receive,save,close,globalBusy,visible,closeRequest}:Props){
 const {confirm,dialog}=useConfirmation();
 const [text,setText]=useState(''),[config,setConfig]=useState<boolean|null>(null),[localTest,setLocalTest]=useState(false),[phase,setPhase]=useState<'idle'|'permission'|'recording'|'recognizing'|'chatting'>('idle'),[error,setError]=useState(''),[drafts,setDrafts]=useState<Draft[]>([]),[panel,setPanel]=useState<'chat'|'plans'>('chat'),[proposalBusy,setProposalBusy]=useState(false),[nextCursor,setNextCursor]=useState<{at:string;id:string}|null>(null),[audioPart,setAudioPart]=useState(''),[seconds,setSeconds]=useState(0),[speak,setSpeak]=useState(false),[speaking,setSpeaking]=useState(false),[pending,setPending]=useState(''),[audioBusy,setAudioBusy]=useState(false),[hydrated,setHydrated]=useState(false),[retryAudio,setRetryAudio]=useState(false);
 const visibility=useRef(visible);visibility.current=visible;const [waitSeconds,setWaitSeconds]=useState(0);
 const proposalLoad=useRef(0),proposalChannel=useRef<BroadcastChannel|null>(null);
 const chatAttempt=useRef<{id:string;text:string}|null>(null),chatAbort=useRef<AbortController|null>(null),chatLock=useRef(false),savedAudio=useRef<string|null>(null);
 const mounted=useRef(true);const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),token=useRef(0),abort=useRef<AbortController|null>(null),audio=useRef<HTMLAudioElement|null>(null),audioUrl=useRef(''),audioToken=useRef(0),audioAbort=useRef<AbortController|null>(null),list=useRef<HTMLDivElement>(null);
 useEffect(()=>{mounted.current=true;let statusRequest:AbortController;const checkStatus=()=>{statusRequest?.abort();const controller=new AbortController();statusRequest=controller;requestJson('/api/qwen/status',undefined,{signal:controller.signal,timeoutMs:10000}).then((c:any)=>{if(mounted.current&&!controller.signal.aborted){setConfig(!!c.configured);setLocalTest(!!c.localTest)}}).catch(e=>{if(mounted.current&&!controller.signal.aborted)setError(errorMessage(e))})};checkStatus();window.addEventListener('online',checkStatus);window.addEventListener('focus',checkStatus);return()=>{statusRequest?.abort();window.removeEventListener('online',checkStatus);window.removeEventListener('focus',checkStatus);mounted.current=false;chatAbort.current?.abort();token.current++;abort.current?.abort();if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());audioToken.current++;audioAbort.current?.abort();audio.current?.pause();if(audioUrl.current)URL.revokeObjectURL(audioUrl.current)}},[]);
 useEffect(()=>{if(panel==='chat')list.current?.scrollTo({top:list.current.scrollHeight,behavior:'smooth'})},[snapshot.data.messages.length,pending,visible]);
 useEffect(()=>{list.current?.scrollTo({top:panel==='plans'?0:list.current.scrollHeight})},[panel]);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('time-master-chat-input')||'null');if(saved&&typeof saved.text==='string'){setText(saved.text);if(saved.requestId&&saved.requestText===saved.text.trim())chatAttempt.current={id:saved.requestId,text:saved.requestText}}}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;try{if(text)sessionStorage.setItem('time-master-chat-input',JSON.stringify({text,requestId:chatAttempt.current?.id,requestText:chatAttempt.current?.text}));else sessionStorage.removeItem('time-master-chat-input')}catch{}},[text,hydrated]);
 async function loadProposals(cursor?:{at:string;id:string}){const seq=++proposalLoad.current;try{const r=await requestJson<{snapshot:Snapshot;drafts:Draft[];nextCursor:{at:string;id:string}|null}>('/api/qwen/proposals'+(cursor?'?cursor='+encodeURIComponent(JSON.stringify(cursor)):''));if(!mounted.current||seq!==proposalLoad.current)return;receive(r.snapshot);setDrafts(old=>cursor?[...old,...r.drafts.filter(d=>!old.some(v=>v.id===d.id))]:r.drafts);setNextCursor(r.nextCursor)}catch(e){if(mounted.current&&seq===proposalLoad.current)setError('待确认方案暂时未能读取。'+errorMessage(e))}}
 useEffect(()=>{void loadProposals()},[snapshot.revision]);
 useEffect(()=>{const refresh=()=>{void loadProposals()};window.addEventListener('focus',refresh);if(typeof BroadcastChannel!=='undefined'){proposalChannel.current=new BroadcastChannel('time-master-proposals');proposalChannel.current.onmessage=refresh}return()=>{proposalLoad.current++;window.removeEventListener('focus',refresh);proposalChannel.current?.close()}},[]);
 useEffect(()=>{if(phase!=='chatting'){setWaitSeconds(0);return}const timer=setInterval(()=>setWaitSeconds(s=>s+1),1000);return()=>clearInterval(timer)},[phase]);
 useEffect(()=>{if(!visible)stopAudio()},[visible]);
 async function requestClose(){if(phase==='recording'){if(!await confirm('结束这次录音并收起？识别会继续，重新打开后可查看文字或重试。'))return;finish();}if(phase==='permission')cancel();stopAudio();close();}
 closeRequest.current=()=>{void requestClose()};
 function reviewDraft(draft:Draft){try{if(!draft.baseline&&draft.workRevision!==snapshot.data.workRevision)return {blocked:draft.blocked||'这份早期方案需要按最新情况重新整理。',operations:draft.operations,warnings:[]};const operations=draft.baseline?mergeChanges(snapshot.data,draft.operations,draft.baseline):draft.operations;return {blocked:'',operations,warnings:changeWarnings(snapshot.data,operations).map(w=>w.message)}}catch{return {blocked:'方案涉及的内容已改变，请按最新情况重新整理。',operations:draft.operations,warnings:[]}}}
 const ready=hydrated&&phase==='idle'&&!globalBusy&&!proposalBusy;
 function stopAudio(){audioToken.current++;audioAbort.current?.abort();audio.current?.pause();if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current='';setSpeaking(false);setAudioBusy(false);}
 async function read(text:string){
  if(!visibility.current)return;stopAudio();const current=audioToken.current,controller=new AbortController();audioAbort.current=controller;setError('');const chunks=speechChunks(text);
  try{for(let i=0;i<chunks.length;i++){
   if(current!==audioToken.current||!mounted.current)return;
   setAudioPart(chunks.length>1?`第 ${i+1}/${chunks.length} 段`:'');setAudioBusy(true);
   const blob=await requestAudio('/api/qwen/tts',{text:chunks[i]},{signal:controller.signal});
   if(current!==audioToken.current||!mounted.current)return;
   const url=URL.createObjectURL(blob);audioUrl.current=url;const a=new Audio(url);audio.current=a;
   try{await new Promise<void>((resolve,reject)=>{
    const cleanup=()=>{a.onended=null;a.onerror=null;controller.signal.removeEventListener('abort',cancelPlay)};
    const finish=()=>{cleanup();resolve()},fail=()=>{cleanup();reject(new Error('语音播放中断，请重新朗读。'))};
    const cancelPlay=()=>{cleanup();a.pause();reject(new DOMException('cancelled','AbortError'))};
    a.onended=finish;a.onerror=fail;controller.signal.addEventListener('abort',cancelPlay,{once:true});
    if(controller.signal.aborted){cancelPlay();return}
    a.play().then(()=>{if(current===audioToken.current&&mounted.current){setAudioBusy(false);setSpeaking(true)}}).catch(fail);
   })}finally{URL.revokeObjectURL(url);if(audioUrl.current===url)audioUrl.current=''}
  }}catch(e){if(current===audioToken.current&&mounted.current)setError(errorMessage(e))}finally{if(current===audioToken.current&&mounted.current){setAudioBusy(false);setSpeaking(false);setAudioPart('')}}
 }
 async function send(){if(!text.trim()||!ready||chatLock.current)return;const value=text.trim();chatLock.current=true;if(chatAttempt.current?.text!==value)chatAttempt.current={id:crypto.randomUUID(),text:value};const attempt=chatAttempt.current;try{sessionStorage.setItem('time-master-chat-input',JSON.stringify({text:value,requestId:attempt.id,requestText:value}))}catch{}setError('');setPhase('chatting');setPanel('chat');setPending(value);stopAudio();const controller=new AbortController();chatAbort.current=controller;try{const r=await requestJson('/api/qwen/chat',{text:value,revision:snapshot.revision,requestId:attempt.id},{signal:controller.signal});receive(r.snapshot);if(!mounted.current)return;proposalLoad.current++;if(r.draft){setDrafts(old=>[{...r.draft,requestText:value},...old.filter(d=>d.id!==r.draft.id)]);setPanel('plans')}setText('');chatAttempt.current=null;try{sessionStorage.removeItem('time-master-chat-input')}catch{}if(r.notice)setError(r.notice);if(speak&&visibility.current)void read(r.reply)}catch(e){if(mounted.current){if(e instanceof ClientError&&e.status===410){chatAttempt.current=null;try{sessionStorage.setItem('time-master-chat-input',JSON.stringify({text:value}))}catch{}}setError(errorMessage(e)+' 文字已保留，点击发送可重试。')}}finally{chatLock.current=false;if(mounted.current){setPhase('idle');setPending('')}}}
 async function recognize(base64:string,current:number){savedAudio.current=base64;setRetryAudio(false);setPhase('recognizing');setError('');const controller=new AbortController();abort.current=controller;try{const r=await requestJson('/api/qwen/asr',{audio:base64},{signal:controller.signal});if(current===token.current){setText(t=>t?t+'\n'+r.text:r.text);savedAudio.current=null;setError('')}}catch(e){if(current===token.current){setRetryAudio(true);setError(errorMessage(e)+' 录音暂存在当前页面，收起后仍可重试识别。刷新前请先重试。')}}finally{if(current===token.current)setPhase('idle')}}
 async function retryRecognition(){if(savedAudio.current&&ready)await recognize(savedAudio.current,++token.current)}
 function cancel(){token.current++;abort.current?.abort();if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setPhase('idle');setSeconds(0);savedAudio.current=null;setRetryAudio(false);}
 function finish(){if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());}
 async function record(){if(!ready)return;savedAudio.current=null;setRetryAudio(false);setError('');stopAudio();if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('当前浏览器不支持录音，请使用新版 Chrome / Edge，或直接输入。');return}const current=++token.current;setPhase('permission');try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(current!==token.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));const rec=new MediaRecorder(s,mime?{mimeType:mime}:undefined);recorder.current=rec;const chunks:Blob[]=[];let bytes=0;rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>5500000)finish()}};rec.onerror=()=>{cancel();setError('录音被中断，请重新录制。')};rec.onstop=async()=>{s.getTracks().forEach(t=>t.stop());if(current!==token.current)return;setPhase('recognizing');const blob=new Blob(chunks,{type:rec.mimeType.split(';')[0]||'audio/webm'});if(blob.size<500){setError('录音太短，请再说一次。');setPhase('idle');return}try{const wav=await recordingToWav(blob);const base64=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=reject;f.readAsDataURL(wav)});if(current!==token.current)return;await recognize(base64,current)}catch(e){if(current===token.current)setError(errorMessage(e))}finally{if(current===token.current)setPhase('idle')}};rec.start(250);setSeconds(0);setPhase('recording');let elapsed=0;timer.current=setInterval(()=>{elapsed++;setSeconds(elapsed);if(elapsed>=60)finish()},1000)}catch(e){if(current===token.current){cancel();setError(e instanceof DOMException&&e.name==='NotAllowedError'?'麦克风权限未开启。可以在浏览器地址栏授权，或直接输入。':'无法启用麦克风，请检查设备后重试。')}}}
 async function apply(draft:Draft){
  if(!ready||reviewDraft(draft).blocked)return;
  setProposalBusy(true);proposalLoad.current++;
  try{if(await save(draft.operations,draft.summary,{workRevision:draft.workRevision,operationId:draft.id})){proposalLoad.current++;setDrafts(old=>old.filter(d=>d.id!==draft.id));proposalChannel.current?.postMessage('changed')}}catch(e){setError(errorMessage(e))}finally{setProposalBusy(false)}
 }
 async function dismiss(draft:Draft){if(!ready)return;setProposalBusy(true);proposalLoad.current++;try{await requestJson('/api/qwen/proposals',{id:draft.id});proposalLoad.current++;setDrafts(old=>old.filter(d=>d.id!==draft.id));proposalChannel.current?.postMessage('changed')}catch(e){setError(errorMessage(e))}finally{setProposalBusy(false)}}
 return <>{dialog}<aside className="assistant-panel" hidden={!visible}><div className="assistant-header"><div className="row"><div className="assistant-symbol"><AudioLines size={19}/></div><div><strong>时间伙伴</strong><span><i className={config?'online-dot':'offline-dot'}/>{config?(localTest?'Qwen · 本机测试':'Qwen 已配置'):config===null?'检查连接…':'等待配置 Qwen'}</span></div></div><button onClick={requestClose} className="icon-button" aria-label="收起时间伙伴"><X size={17}/></button></div><div className="assistant-intro"><h2>聊一聊，理清下一步。</h2><p>说说项目或日程，安排经你确认后生效。</p></div><div className="assistant-tabs"><button className={panel==='chat'?'selected':''} onClick={()=>setPanel('chat')}>对话</button><button className={panel==='plans'?'selected':''} onClick={()=>setPanel('plans')}>待确认方案 {drafts.length>0&&<span>{drafts.length}{nextCursor?'+':''}</span>}</button></div><div className="chat-scroll" ref={list}> {panel==='chat'&&<>
 {!snapshot.data.messages.length&&<div className="starter-prompts"><small>可以从这里开始</small>{['看看我目前哪些项目需要推进','今天有什么可以优先做的？','帮我为一个事项安排专注时间'].map(s=><button key={s} onClick={()=>setText(s)}>{s}<ArrowUp size={13}/></button>)}</div>}
 {snapshot.data.messages.map(m=><div key={m.id} className={'message '+m.role}><small>{m.role==='user'?'你':'时间伙伴'}</small><p>{m.content}</p>{m.role==='assistant'&&<button className="read-button" disabled={!config||audioBusy} onClick={()=>read(m.content)}><Volume2 size={13}/>朗读</button>}</div>)}
 {pending&&<><div className="message user"><small>你</small><p>{pending}</p></div><div className="thinking"><Loader2 size={14} className="spin"/>{waitSeconds<12?'正在梳理你的安排…':'正在等待 Qwen 回复 · '+waitSeconds+' 秒，输入已保留'}<button className="text-button" onClick={()=>chatAbort.current?.abort()}>停止等待</button></div></>}
 </>} {panel==='plans'&&<>{!drafts.length&&<div className="plans-empty"><Sparkles size={24}/><p>还没有待确认的方案</p><small>聊聊你想安排的事，方案会保留在这里。</small><button className="text-button" onClick={()=>{void loadProposals()}}>刷新方案</button></div>}{drafts.map(draft=>{const reviewed=reviewDraft(draft);return <div className="draft-card" key={draft.id}><div className="row"><Sparkles size={15}/><strong>待应用的安排</strong></div><p>{draft.summary}</p>{reviewed.operations.map((o,i)=>{const l=operationLabel(o,snapshot.data);return <div className="draft-item" key={i}><span className={l.verb==='删除'?'danger-text':''}>{l.verb} · {l.name}</span>{l.value?.start&&<small>{l.value.start.replace('T',' ')} → {l.value.end?.replace('T',' ')}</small>}{l.value?.status&&<small>状态：{({active:'推进中',paused:'暂停',done:'已完成',doing:'进行中',waiting:'等待',todo:'待开始'} as any)[l.value.status]}</small>}<details><summary>查看完整变更 <ChevronDown size={11}/></summary><ChangeDetails operation={o} snapshot={snapshot}/></details></div>})}{reviewed.warnings.length>0&&<div className="plan-warnings"><strong>根据最新安排检查</strong>{reviewed.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}{reviewed.blocked?<div className="stale-plan"><p>{reviewed.blocked}</p><button className="text-button" disabled={!ready} onClick={()=>{setText(draft.requestText||draft.summary);setPanel('chat')}}>按最新情况重新整理</button></div>:<button className="primary full" disabled={!ready} onClick={()=>apply(draft)}><Check size={15}/>应用 {draft.operations.length} 项安排</button>}<button className="text-button full" disabled={!ready} onClick={()=>dismiss(draft)}>放弃这次方案</button></div>})}{nextCursor&&<button className="secondary full" onClick={()=>{void loadProposals(nextCursor)}}>查看更早的待确认方案</button>}</>}
 </div><div className="composer"><div className="voice-preference"><label><input type="checkbox" checked={speak} onChange={e=>setSpeak(e.target.checked)}/>语音回复</label>{(speaking||audioBusy)&&<button className="text-button" onClick={stopAudio}><Square size={11}/>{audioBusy?'取消生成':'停止朗读'} {audioPart}</button>}</div>{error&&<div className="assistant-error" role="alert">{error}{retryAudio&&<button className="text-button" disabled={!ready} onClick={retryRecognition}>重试识别</button>}</div>}{config===false&&<p className="setup-note">Qwen 尚未配置。项目和日程可正常使用。</p>}
 <div className={'input-box '+(phase==='recording'?'recording':'')}><textarea aria-label="和时间伙伴聊天" value={text} onChange={e=>setText(e.target.value)} placeholder={phase==='recording'?'正在听你说…':'说说你想安排的事…'} maxLength={8000} disabled={phase==='chatting'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><div className="composer-actions">{phase==='recording'?<button onClick={finish} className="record-stop"><Square size={14}/>说完了 · {seconds}s</button>:phase==='permission'||phase==='recognizing'?<span className="small muted"><Loader2 size={14} className="spin"/>{phase==='permission'?'等待麦克风权限…':'Qwen 正在识别…'}</span>:<button className="mic-button" disabled={!ready||!config} onClick={record} aria-label="开始 Qwen 语音输入"><Mic size={18}/><span>语音输入</span></button>}{['permission','recording','recognizing'].includes(phase)?<button className="text-button" onClick={cancel}>取消</button>:<button className="send-button" aria-label="发送消息" disabled={!text.trim()||!ready||!config} onClick={send}>{phase==='chatting'?<Loader2 className="spin" size={17}/>:<ArrowUp size={18}/>}</button>}</div></div><p className="composer-hint">识别后可编辑文字 · Enter 发送 · 修改经你确认后生效</p></div></aside></>;
}
