'use client';
import RecoveryDialog from './recovery-dialog';
import {useRef,useState} from 'react';
import {Upload,X} from 'lucide-react';
import {parseBackup,businessKeys,type BackupData,type RestoreMode} from '@/lib/backup';
import {requestJson,ClientError,errorMessage} from '@/lib/api-client';
import {type Snapshot} from '@/lib/domain';
type Preview={counts:Record<string,number>;warnings:string[];total:number;workRevision:number};
const labels={projects:'项目',tasks:'事项',blocks:'日程',contacts:'联系人',resources:'工程位置',captures:'随手记',followups:'跟进'};
export default function BackupRestore({receive,notify,disabled}:{receive:(s:Snapshot)=>void;notify:(text:string,error?:boolean)=>void;disabled:boolean}){
 const input=useRef<HTMLInputElement>(null),[file,setFile]=useState<{name:string;data:BackupData}|null>(null),[mode,setMode]=useState<RestoreMode>('missing'),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const attempt=useRef(crypto.randomUUID()),lock=useRef(false);
 async function inspect(data:BackupData,selected:RestoreMode){setPreview(null);setError('');setBusy(true);try{setPreview(await requestJson<Preview>('/api/workspace/restore',{data,mode:selected,requestId:attempt.current,preview:true}))}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function choose(f:File){if(f.size>8000000){notify('备份超过 8 MB，请选择较小的备份。',true);return}try{const data=parseBackup(JSON.parse(await f.text()));attempt.current=crypto.randomUUID();setMode('missing');setFile({name:f.name,data});await inspect(data,'missing')}catch(e){notify('无法读取备份：'+errorMessage(e),true)}}
 async function restore(){if(!file||!preview||busy||disabled||lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await requestJson<{snapshot:Snapshot;applied:boolean;empty?:boolean}>('/api/workspace/restore',{data:file.data,mode,requestId:attempt.current,reviewedRevision:preview.workRevision});receive(r.snapshot);setFile(null);setPreview(null);notify(r.empty?'没有需要恢复的缺失记录。':'备份已恢复，现有内容已保留。')}catch(e){if(e instanceof ClientError&&e.details?.code==='RESTORE_REVIEW'){receive(e.details.snapshot);setPreview(e.details.preview);setError('工作空间有新安排，已更新预览，请再次核对后恢复。')}else setError(errorMessage(e)+' 预览和本次请求已保留，可以重试。')}finally{lock.current=false;setBusy(false)}}
 return <><input ref={input} type="file" accept="application/json,.json" hidden aria-label="选择工作空间备份" onChange={e=>{const f=e.target.files?.[0];if(f)void choose(f);e.target.value=''}}/><button className="text-button" disabled={disabled||busy} onClick={()=>input.current?.click()}><Upload size={15}/>恢复备份</button>{file&&<RecoveryDialog label="恢复备份" busy={busy} close={()=>setFile(null)}><div className="row between"><h2>恢复备份</h2><button className="icon-button" aria-label="关闭恢复预览" disabled={busy} onClick={()=>setFile(null)}><X/></button></div><p>{file.name}</p><p>恢复项目、事项、日程、联系人、工程位置、随手记和跟进。当前聊天记录和推进历史保留。</p><label>恢复方式<select value={mode} disabled={busy} onChange={e=>{const next=e.target.value as RestoreMode;setMode(next);attempt.current=crypto.randomUUID();void inspect(file.data,next)}}><option value="missing">补回缺失记录，保留已有内容</option><option value="copies">完整恢复为独立副本</option></select></label><small>{mode==='missing'?'同编号记录不覆盖。为容纳恢复事项，项目日期可能扩大，预览会明确说明；若需找回旧版本或全部关联，请选择独立副本。':'备份内关联会一起恢复，新项目标记为“恢复副本”，可能与当前日程重叠。'}</small>{busy&&!preview&&<p role="status">正在检查备份与当前安排…</p>}{preview&&<><div className="restore-counts">{businessKeys.map(k=><span key={k}>{labels[k]} <strong>{preview.counts[k]}</strong></span>)}</div><details><summary>备份中的项目</summary><ul>{file.data.projects.map(p=><li key={p.id}>{p.name} · {p.start} → {p.end}</li>)}</ul></details>{preview.warnings.length>0&&<div className="plan-warnings"><strong>恢复前需要留意</strong>{preview.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}{!preview.total&&<p>未发现缺失记录。如需找回旧版本，可选择完整恢复为独立副本。</p>}</>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="row recovery-actions"><button className="secondary" disabled={busy} onClick={()=>setFile(null)}>取消</button>{!preview?<button className="primary" disabled={busy} onClick={()=>inspect(file.data,mode)}>重新预览</button>:<button className="primary" disabled={busy||disabled||!preview.total} onClick={restore}>{busy?'正在恢复…':'确认恢复 '+preview.total+' 条记录'}</button>}</div></RecoveryDialog>}</>;
}
