'use client';
import {useEffect,useRef,useState} from 'react';
import {Inbox,ArrowUpRight,Clock,Check,CalendarPlus,Plus,RotateCcw} from 'lucide-react';
import {localDay,addDays,type Snapshot,type Capture,type Followup,type Operation} from '@/lib/domain';
import {captureBaseline,type ChangeBaseline} from '@/lib/changes';
import {rebaseSubmittedOperations} from '@/lib/editor-draft';
import {type OperationReceipt} from '@/lib/workspace-storage';
import {beijingNow,convertCapture,completeFollowup,reviewCounts,type DayPlanInput} from '@/lib/daily-planning';
import {followupCalendar} from '@/lib/calendar-export';
import {requestJson,errorMessage} from '@/lib/api-client';
import {type SaveWorkspace} from './use-workspace';
import {type EditItem} from './editor';
import RecoveryDialog from './recovery-dialog';

type Props={snapshot:Snapshot;save:SaveWorkspace;busy:boolean;open:(v:EditItem)=>void;receive:(s:Snapshot)=>void;notify:(s:string,error?:boolean)=>void};
type Mode='desk'|'inbox'|'followups';
export default function DailyWork(props:Props&{mode:Mode}){
 const {snapshot:{data},mode,open,busy}=props,today=localDay();
 const [view,setView]=useState('active'),[convert,setConvert]=useState<Capture|null>(null),[convertKind,setConvertKind]=useState<'task'|'followup'>('task'),[reschedule,setReschedule]=useState<Followup|null>(null);
 const [now,setNow]=useState(beijingNow());useEffect(()=>{const t=setInterval(()=>setNow(beijingNow()),30000);return()=>clearInterval(t)},[]);
 const captures=data.captures.filter(c=>view==='archive'?c.status!=='inbox':c.status==='inbox'&&(!c.reviewOn||c.reviewOn<=today));
 const deferred=data.captures.filter(c=>c.status==='inbox'&&c.reviewOn>today);
 const waiting=data.followups.filter(f=>view==='archive'?f.status!=='waiting':f.status==='waiting').sort((a,b)=>a.dueAt.localeCompare(b.dueAt));
 const due=waiting.filter(f=>f.dueAt<=now&&f.status==='waiting'),counts=reviewCounts(data);
 function calendar(items:Followup[]){const blob=new Blob([followupCalendar(data,items)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='时间管理大师-跟进提醒.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);props.notify('已导出日历文件，请导入系统日历并确认提醒已开启。')}
 async function changeCapture(c:Capture,status:Capture['status']){await props.save([{type:'capture.save',data:{...c,status}}],status==='inbox'?'重新整理：'+c.name:'归档随手记：'+c.name)}
 function followupCard(f:Followup){const contact=data.contacts.find(c=>c.id===f.contactId),task=data.tasks.find(t=>t.id===f.taskId);return <article className="work-card" key={f.id}><div className="row between"><span className={'work-badge '+(f.status==='waiting'&&f.dueAt<=now?'due':'')}>{f.status==='resolved'?'已收到 / 已解决':f.status==='cancelled'?'已取消':f.dueAt<=now?'到时间跟进':'等待中'}</span><button className="text-button" onClick={()=>open({kind:'followup',id:f.id})}>编辑</button></div><h3>{f.name}</h3><p>{f.notes||'下次联系时，补充结果和下一步。'}</p><div className="work-meta"><span><Clock size={14}/>{f.dueAt.replace('T',' ')}</span><span>{contact?.name||'联系人待确定'}{contact?.wechat?' · '+contact.wechat:''}</span></div>{task&&<button className="task-link" onClick={()=>open({kind:'task',id:task.id})}>{f.blocksTask?'影响：':'关联：'}{task.name}<ArrowUpRight size={14}/></button>}{f.lastContactAt&&<small className="muted">上次联系：{f.lastContactAt.replace('T',' ')}</small>}<div className="work-actions">{f.status==='waiting'?<><button className="secondary" disabled={busy} onClick={()=>props.save(completeFollowup(f),'跟进已解决：'+f.name)}><Check size={14}/>已收到 / 已解决</button><button className="text-button" disabled={busy} onClick={()=>setReschedule(f)}>已联系 / 改时间</button><button className="icon-button" aria-label={'导出'+f.name+'提醒'} onClick={()=>calendar([f])}><CalendarPlus size={17}/></button></>:<button className="text-button" disabled={busy} onClick={()=>setReschedule(f)}><RotateCcw size={14}/>重新等待</button>}</div></article>}
 return <div className="daily-work">
 {mode==='desk'&&<div className="day-pulse"><div><span>先收下，再一步步处理</span><h2>今天，把精力用在值得的地方。</h2></div><div className="pulse-counts"><span><b>{counts.inbox}</b>待整理</span><span><b>{counts.followups}</b>今天需跟进</span><span><b>{counts.done}</b>已完成时段</span></div></div>}
 {(mode==='desk'||mode==='inbox')&&<QuickCapture {...props}/>}
 {mode==='desk'&&<><DayPlanner {...props}/><div className="work-section-heading"><h2>今天需要接住的事</h2><span>{due.length} 条跟进到时间</span></div><div className="work-grid">{due.slice(0,6).map(followupCard)}{!due.length&&<div className="work-empty">暂时没有到时间的跟进。等待资料或反馈时，记下下次联系的时间。</div>}</div><section className="daily-review"><h3>收尾时，留一小步给明天</h3><p>{counts.unfinished?`今天还有 ${counts.unfinished} 段安排未标记完成。完成了一部分，就更新事项的剩余投入；没有做的，再决定是否改期。`:'今天的安排和结果可以随时核对。完成一个时段，不等于整个事项已经完成。'}</p><div className="review-items">{data.blocks.filter(b=>!b.done&&b.start.slice(0,10)===today).slice(0,6).map(b=><button className="text-button" key={b.id} onClick={()=>open({kind:b.taskId?'task':'block',id:b.taskId||b.id})}>{b.name}<ArrowUpRight size={14}/></button>)}</div></section></>}
 {mode!=='desk'&&<div className="work-section-heading"><div className="work-tabs"><button className={view==='active'?'selected':''} onClick={()=>setView('active')}>{mode==='inbox'?'待整理':'等待与跟进'}</button><button className={view==='archive'?'selected':''} onClick={()=>setView('archive')}>已处理</button></div>{mode==='followups'&&<button className="text-button" disabled={!waiting.some(f=>f.status==='waiting')} onClick={()=>calendar(waiting)}><CalendarPlus size={16}/>导出系统日历提醒</button>}</div>}
 {mode==='inbox'&&<><div className="work-grid">{captures.map(c=><article className="work-card" key={c.id}><div className="row between"><span className="work-badge">{c.status==='converted'?'已整理':c.status==='archived'?'已归档':'先记着'}</span><button className="text-button" onClick={()=>open({kind:'capture',id:c.id})}>补充 / 编辑</button></div><h3>{c.name}</h3>{c.notes&&<p className="capture-notes">{c.notes}</p>}<small className="muted">{c.createdAt?new Date(c.createdAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'早前记录'}</small><div className="work-actions">{c.status==='inbox'?<><button className="secondary" disabled={busy} onClick={()=>{setConvertKind('task');setConvert(c)}}>整理成事项</button><button className="text-button" disabled={busy} onClick={()=>{setConvertKind('followup');setConvert(c)}}>建立跟进</button><button className="text-button" disabled={busy} onClick={()=>changeCapture(c,'archived')}>暂不做，归档</button></>:<>{c.followupId&&<button className="secondary" onClick={()=>open({kind:'followup',id:c.followupId})}>查看跟进</button>}{c.taskId&&<button className="secondary" onClick={()=>open({kind:'task',id:c.taskId})}>查看事项</button>}<button className="text-button" disabled={busy} onClick={()=>changeCapture(c,'inbox')}>重新整理</button></>}</div></article>)}</div>{!captures.length&&<div className="work-empty"><Inbox size={24}/><p>{view==='archive'?'处理过的记录会保留在这里。':'想到一件事，先放进来。不必现在决定什么时候做。'}</p></div>}{view==='active'&&deferred.length>0&&<details className="deferred-captures"><summary>以后再看 · {deferred.length} 条</summary>{deferred.map(c=><button className="text-button" key={c.id} onClick={()=>open({kind:'capture',id:c.id})}>{c.reviewOn} · {c.name}</button>)}</details>}</>}
 {mode==='followups'&&<><p className="field-note">这里记录你要跟进的事，不会代发微信。关闭网页后需要提醒，可导入系统日历；网站改期后需重新导出核对。</p><div className="work-grid">{waiting.map(followupCard)}</div>{!waiting.length&&<div className="work-empty"><h3>让等待有个下次。</h3><p>等名单、等设计图、等客户确认，都可以记下跟谁联系、何时再问。</p><button className="secondary" onClick={()=>open({kind:'followup'})}><Plus size={15}/>添加跟进</button></div>}</>}
 {convert&&<CaptureConversion {...props} capture={convert} kind={convertKind} close={()=>setConvert(null)}/>}
 {reschedule&&<FollowupReschedule {...props} followup={reschedule} close={()=>setReschedule(null)}/>}
 </div>;
}

function QuickCapture({save,busy,snapshot}:Props){
 const key='time-master-capture:'+snapshot.scope,[text,setText]=useState(''),[attempt,setAttempt]=useState<{id:string;text:string;at:string}|null>(null),[error,setError]=useState(''),[hydrated,setHydrated]=useState(false),lock=useRef(false);
 useEffect(()=>{try{const stored=JSON.parse(sessionStorage.getItem(key)||'null');if(stored){setText(stored.text||'');setAttempt(stored.attempt||null)}}catch{}setHydrated(true)},[key]);
 useEffect(()=>{if(hydrated)try{if(text)sessionStorage.setItem(key,JSON.stringify({text,attempt}));else sessionStorage.removeItem(key)}catch{}},[text,attempt,hydrated,key]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||lock.current||!text.trim())return;lock.current=true;setError('');const a=attempt||{id:crypto.randomUUID(),text:text.trim(),at:new Date().toISOString()};setAttempt(a);const op:Operation={type:'capture.save',data:{id:a.id,name:a.text.split('\n')[0].slice(0,160),notes:a.text,status:'inbox',createdAt:a.at}};try{const ok=await save([op],'随手记：'+a.text.slice(0,60),{operationId:'capture-'+a.id,baseline:{records:[{kind:'capture',id:a.id,value:null}],deletions:{}}});if(ok){setText('');setAttempt(null)}else setError('保存结果尚未确认，原文已保留。点击重试，不会重复记。')}finally{lock.current=false}}
 return <form className="quick-capture" onSubmit={submit}><label htmlFor="quick-capture">脑子里的事，先放在这里</label><textarea id="quick-capture" placeholder="比如：想学剪辑，还没想好什么时候；等小林发图后看看…" value={text} maxLength={8000} readOnly={!!attempt} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')e.currentTarget.form?.requestSubmit()}}/><div className="row between"><span className="muted small">不用选项目，不占日历 · Ctrl / ⌘ + Enter</span><button className="primary" disabled={!hydrated||busy||!text.trim()}>{attempt?'重试保存':'先记下来'}<Plus size={15}/></button></div>{error&&<p role="alert">{error}</p>}</form>;
}

function CaptureConversion({capture,snapshot,save,busy,close,kind,receive:propsReceive}:Props&{capture:Capture;kind:'task'|'followup';close:()=>void}){
 const initial=useRef(snapshot.data),id=useRef(crypto.randomUUID()),operationId=useRef(crypto.randomUUID()),createdAt=useRef(new Date().toISOString()),[error,setError]=useState(''),[saving,setSaving]=useState(false),attempt=useRef<{ops:Operation[];baseline:ChangeBaseline;summary:string;id:string}|null>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(saving||busy)return;const f=new FormData(e.currentTarget),v=(k:string)=>String(f.get(k)||'');try{setSaving(true);let ops:Operation[]=kind==='task'?convertCapture(initial.current,capture,{projectId:v('projectId'),start:v('start'),end:v('end'),hours:Number(v('hours'))},id.current):[{type:'followup.save',data:{id:id.current,name:capture.name,notes:capture.notes,projectId:v('projectId'),contactId:v('contactId'),dueAt:v('dueAt'),status:'waiting',createdAt:createdAt.current}},{type:'capture.save',data:{...capture,status:'converted',followupId:id.current,projectId:v('projectId'),taskId:'',reviewOn:''}}];ops=ops.map(op=>op.type==='task.save'||op.type==='followup.save'?{...op,data:{...op.data as object,name:v('name')}}:op);let baseline=captureBaseline(initial.current,ops);const previous=attempt.current;
if(previous&&JSON.stringify(previous.ops)!==JSON.stringify(ops)){const r=await requestJson<{snapshot:Snapshot;receipt:OperationReceipt}>('/api/workspace/operations',{operationId:previous.id,ops:previous.ops,baseline:previous.baseline,summary:previous.summary});propsReceive(r.snapshot);ops=rebaseSubmittedOperations(previous.ops,ops,r.receipt);baseline={records:baseline.records.map(b=>r.receipt.status==='applied'?r.receipt.records.find(v=>v.kind===b.kind&&v.id===b.id)||b:b),deletions:baseline.deletions};operationId.current=crypto.randomUUID();}
attempt.current={ops,baseline:previous&&JSON.stringify(previous.ops)===JSON.stringify(ops)?previous.baseline:baseline,summary:'整理随手记：'+capture.name,id:operationId.current};const a=attempt.current;
const ok=await save(a.ops,a.summary,{operationId:a.id,baseline:a.baseline});if(ok)close();else setError('没有确认保存成功。输入仍保留，请重试；若记录已被别处整理，请关闭后查看最新记录。')}catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
 return <RecoveryDialog label="整理成事项" busy={saving||busy} close={close}><form onSubmit={submit}><h2>{kind==='task'?'准备好，再变成一个事项':'为这件事留下次跟进'}</h2><p>{capture.name}</p><p className="muted">原文会保留，事项与原记录一起保存。</p><fieldset disabled={saving||busy}><label>{kind==='task'?'事项名称':'跟进什么'}<input name="name" required maxLength={160} defaultValue={capture.name}/></label><label>所属项目<select name="projectId" required={kind==='task'} defaultValue={capture.projectId||''}><option value="">选择项目</option>{snapshot.data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{kind==='task'&&!snapshot.data.projects.length&&<p>还没有项目。可以先保留这条随手记，创建项目后再整理。</p>}{kind==='task'?<><div className="field-grid"><label>预计开始<input name="start" type="date" required/></label><label>预计结束<input name="end" type="date" required/></label></div><label>预计投入（小时）<input name="hours" type="number" min="0.25" max="10000" step="0.25" required/></label></>:<><label>下次跟进<input name="dueAt" type="datetime-local" required/></label><label>联系人<select name="contactId"><option value="">稍后补充</option>{snapshot.data.contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}</fieldset>{error&&<p role="alert">{error}</p>}<div className="work-actions"><button className="primary" disabled={saving||busy||kind==='task'&&!snapshot.data.projects.length}>确认整理</button><button type="button" className="secondary" disabled={saving||busy} onClick={close}>继续留在收件箱</button></div></form></RecoveryDialog>;
}
function FollowupReschedule({followup:f,snapshot,save,busy,close,receive}:Props&{followup:Followup;close:()=>void}){
 const initial=useRef(snapshot.data),at=useRef(beijingNow()),[error,setError]=useState(''),[saving,setSaving]=useState(false),attempt=useRef<{ops:Operation[];baseline:ChangeBaseline;summary:string;id:string}|null>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(saving||busy)return;const form=new FormData(e.currentTarget),notes=String(form.get('notes')||'');setSaving(true);setError('');try{
 let ops:Operation[]=[{type:'followup.save',data:{...f,status:'waiting',resolvedAt:'',dueAt:String(form.get('dueAt')),blocksTask:!!f.taskId&&form.has('blocksTask'),lastContactAt:form.has('contacted')?at.current:f.lastContactAt,notes:notes?f.notes+'\n'+at.current+' · '+notes:f.notes}}];
 let baseline=captureBaseline(initial.current,ops),id=crypto.randomUUID();const previous=attempt.current;
 if(previous){if(JSON.stringify(previous.ops)===JSON.stringify(ops)){baseline=previous.baseline;id=previous.id}else{const r=await requestJson<{snapshot:Snapshot;receipt:OperationReceipt}>('/api/workspace/operations',{operationId:previous.id,ops:previous.ops,baseline:previous.baseline,summary:previous.summary});receive(r.snapshot);ops=rebaseSubmittedOperations(previous.ops,ops,r.receipt);baseline={records:baseline.records.map(b=>r.receipt.status==='applied'?r.receipt.records.find(v=>v.kind===b.kind&&v.id===b.id)||b:b),deletions:baseline.deletions};}}
 attempt.current={ops,baseline,summary:'更新跟进时间：'+f.name,id};if(await save(ops,attempt.current.summary,{baseline,operationId:id}))close();else setError('暂未确认保存，输入已保留。重试会核对上次结果，不会重复追加联系记录。');
 }catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
 return <RecoveryDialog label="更新跟进时间" busy={busy||saving} close={close}><form onSubmit={submit}><h2>{f.name}</h2><fieldset disabled={busy||saving}><label>下次跟进<input type="datetime-local" name="dueAt" required defaultValue={addDays(localDay(),1)+'T10:00'}/></label><label>这次的结果 / 还缺什么<textarea name="notes" placeholder="例如：名单只到一半，周一再问剩下的" maxLength={1500}/></label><label className="check-row"><input name="contacted" type="checkbox" defaultChecked={f.status==='waiting'}/>我已经联系过对方</label>{f.taskId&&<label className="check-row"><input name="blocksTask" type="checkbox" defaultChecked={f.blocksTask}/>收到结果前，关联事项暂不能推进</label>}</fieldset>{error&&<p role="alert">{error}</p>}<div className="work-actions"><button className="primary" disabled={busy||saving}>保存下次跟进</button><button type="button" className="secondary" disabled={busy||saving} onClick={close}>取消</button></div></form></RecoveryDialog>;
}
function DayPlanner({snapshot,receive,busy,open}:Props){
 const [input,setInput]=useState<DayPlanInput>(()=>{const time=beijingNow().slice(11),tomorrow=time>='17:45';return {date:tomorrow?addDays(localDay(),1):localDay(),start:tomorrow?'09:00':time,end:tomorrow?'12:00':'18:00',minutes:120,energy:'focus'}}),[preview,setPreview]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),requestId=useRef(crypto.randomUUID()),lock=useRef(false);
 const set=(key:keyof DayPlanInput,value:string|number)=>{setInput(p=>({...p,[key]:value}));setPreview(null);setError('');requestId.current=crypto.randomUUID()};
 async function plan(apply=false){if(loading||busy||lock.current)return;lock.current=true;setLoading(true);setError('');try{const r=await requestJson<any>('/api/planning',{input,requestId:requestId.current,preview:!apply,...(apply?{reviewedRevision:preview.revision,planHash:preview.planHash}:{})});if(apply){receive(r.snapshot);setPreview(null);requestId.current=crypto.randomUUID();setError('已放入日程。做完一段后，可以核对事项还需多少投入。')}else setPreview(r)}catch(e){setError(errorMessage(e))}finally{setLoading(false);lock.current=false}}
 const risks=snapshot.data.tasks.filter(t=>t.status!=='done'&&t.deadline&&t.deadline<=addDays(input.date,1));
 return <section className="day-planner"><div className="row between"><div><h2>{input.date===localDay()?'今天':input.date===addDays(localDay(),1)?'明天':input.date}还能投入多少？</h2><p>按新增投入来算，已有日程保留。每段最多 60 分钟，不自动延长工作时间。</p></div><Clock size={22}/></div><fieldset disabled={loading||busy} className="planner-fields"><label>日期<input type="date" value={input.date} onChange={e=>set('date',e.target.value)}/></label><label>从<input type="time" value={input.start} onChange={e=>set('start',e.target.value)}/></label><label>到<input type="time" value={input.end} onChange={e=>set('end',e.target.value)}/></label><label>新增投入<select value={input.minutes} onChange={e=>set('minutes',Number(e.target.value))}><option value={30}>30 分钟</option><option value={60}>1 小时</option><option value={120}>2 小时</option><option value={180}>3 小时</option><option value={240}>4 小时</option></select></label><label>现在的精力<select value={input.energy} onChange={e=>set('energy',e.target.value)}><option value="focus">可以专注</option><option value="light">做点轻的</option></select></label></fieldset>{risks.length>0&&<div className="deadline-watch"><strong>临近硬截止，别遗漏</strong>{risks.map(t=><button className="text-button" key={t.id} onClick={()=>open({kind:'task',id:t.id})}>{t.deadline} · {t.name}<ArrowUpRight size={13}/></button>)}</div>}<button className="secondary" disabled={loading||busy} onClick={()=>plan()}>{loading?'正在核对…':'帮我挑选并预览'}</button>{error&&<p role="status">{error}</p>}{preview&&<div className="plan-preview"><p>{preview.explanation}</p>{preview.warnings?.map((w:string,i:number)=><p className="schedule-risk" key={i}>{w}</p>)}{preview.blockedCount>0&&<small className="muted">另有 {preview.blockedCount} 件事项仍在等待条件满足，本次未安排。</small>}{preview.items.map((i:any,index:number)=><div className="plan-slot" key={index}><span>{i.start.slice(11)}—{i.end.slice(11)}</span><div><strong>{i.name}</strong><small>{i.reason}</small></div><b>{i.minutes} 分钟</b></div>)}{preview.items.length>0&&<button className="primary" disabled={loading||busy||preview.revision!==snapshot.revision} onClick={()=>plan(true)}>确认放入日程</button>}{preview.revision!==snapshot.revision&&<p>安排或偏好已更新，请重新预览。</p>}</div>}</section>;
}
