'use client';
import {useConfirmation} from './confirmation';
import {useEffect,useRef,useState} from 'react';
import {X,Trash2,AlertCircle,Folder,Monitor,Users} from 'lucide-react';
import {addDays,localDay,collisions,statusLabels,type Data,type Operation,type Block} from '@/lib/domain';
export type EditKind='project'|'task'|'block'|'contact'|'resource';
export type EditItem={kind:EditKind;id?:string;projectId?:string;taskId?:string;date?:string};
type Props={item:EditItem;data:Data;busy:boolean;close:()=>void;save:(ops:Operation[],summary:string)=>Promise<boolean>};
export default function Editor({item,data,busy,close,save}:Props){
 const {confirm,dialog}=useConfirmation();
 const dirty=useRef(false);const requestClose=async()=>{if(!dirty.current||await confirm('还有未保存的修改，确定关闭吗？'))close()};
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[]);
 const {kind}=item,collection=kind==='project'?data.projects:kind==='task'?data.tasks:kind==='block'?data.blocks:kind==='contact'?data.contacts:data.resources;
 const old=collection.find(v=>v.id===item.id) as any;const title={project:'项目',task:'事项',block:'日程',contact:'联系人',resource:'工程位置'}[kind];
 const today=item.date||localDay(),id=useRef(item.id||crypto.randomUUID()),form=useRef<HTMLFormElement>(null),[error,setError]=useState('');
 const projectId=old?.projectId||item.projectId||data.projects[0]?.id||'';
 useEffect(()=>{const el=form.current;el?.querySelector<HTMLInputElement>('input')?.focus();function key(e:KeyboardEvent){if(e.key==='Escape'&&!busy)requestClose();if(e.key==='Tab'&&el){const list=Array.from(el.querySelectorAll<HTMLElement>('input,button,select,textarea,a[href]')).filter(x=>!x.hasAttribute('disabled'));if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0]?.focus()}}}document.addEventListener('keydown',key);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=previous}},[busy,close]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');const f=new FormData(form.current!);const val=(s:string)=>String(f.get(s)||'');const common={...old,id:id.current,name:val('name')};let value:any;
 if(kind==='project')value={...common,goal:val('goal'),start:val('start'),end:val('end'),status:val('status'),color:val('color')};
 if(kind==='task')value={...common,projectId:val('projectId'),shortName:val('shortName'),description:val('description'),start:val('start'),end:val('end'),status:val('status'),owner:val('owner'),hours:Number(val('hours')),contactId:val('contactId'),dependencies:f.getAll('dependencies').map(String),updatedAt:old?.updatedAt||'',result:val('result')};
 if(kind==='block'){value={...common,taskId:val('taskId'),start:val('start'),end:val('end'),fixed:f.has('fixed'),done:f.has('done')};const overlap=collisions(data,value as Block);if(!value.done&&overlap.length&&!await confirm('此日程与「'+overlap.map(b=>b.name).join('、')+'」时间重叠。仍要保存这段安排吗？'))return;}
 if(kind==='contact')value={...common,wechat:val('wechat'),notes:val('notes'),roles:data.projects.filter(p=>f.has('role-project-'+p.id)).map(p=>({projectId:p.id,role:val('role-'+p.id)}))};
 if(kind==='resource')value={...common,projectId:val('projectId'),device:val('device'),path:val('path'),purpose:val('purpose')};
 const ok=await save([{type:(kind+'.save') as Operation['type'],data:value}],`${old?'更新':'新增'}${title}：${value.name}`);if(ok)close();else setError('未能保存，请查看页面提示并核对输入。');
 }
 async function remove(){const prompt=kind==='project'?'删除该项目及其事项、未完成日程和工程记录？已完成日程会保留，联系人及电脑上的实际文件不受影响。':kind==='task'?'删除该事项及其未完成日程？已完成日程保留，其他事项会解除对它的依赖。':`删除这个${title}？`;if(!await confirm(prompt))return;if(await save([{type:(kind+'.delete') as Operation['type'],id:item.id}],`删除${title}：${old.name}`))close();}
 const dateFields=(withTime=false)=><div className="field-grid"><label>开始{withTime?'时间':'日期'}<input name="start" type={withTime?'datetime-local':'date'} required defaultValue={old?.start||(withTime?today+'T09:00':today)}/></label><label>结束{withTime?'时间':'日期'}<input name="end" type={withTime?'datetime-local':'date'} required defaultValue={old?.end||(withTime?today+'T10:00':addDays(today,kind==='project'?14:2))}/></label></div>;
 const projectField=<label>所属项目<select name="projectId" defaultValue={projectId} required><option value="" disabled>选择项目</option>{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>;
 return <>{dialog}<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)requestClose()}}><form ref={form} className="editor" role="dialog" aria-modal="true" aria-labelledby="editor-title" onSubmit={submit} onInput={()=>{dirty.current=true}} onChange={()=>{dirty.current=true}}><div className="editor-header"><div><span className="eyebrow">让安排更清晰</span><h2 id="editor-title">{old?'编辑':'新建'}{title}</h2></div><button type="button" disabled={busy} className="icon-button" aria-label="关闭编辑" onClick={requestClose}><X/></button></div><div className="editor-body"><label>{title}名称<input name="name" required maxLength={160} defaultValue={old?.name|| (kind==='block'?data.tasks.find(t=>t.id===item.taskId)?.name:'')} placeholder={kind==='project'?'例如：品牌官网第一版':'写下清晰、具体的名称'}/></label>
 {kind==='project'&&<><label>这个项目要达成什么<textarea name="goal" defaultValue={old?.goal} placeholder="目标、交付物，以及完成的标准"/></label>{dateFields()}<div className="field-grid"><label>项目状态<select name="status" defaultValue={old?.status||'active'}><option value="active">推进中</option><option value="paused">暂停</option><option value="done">已完成</option></select></label><label>项目颜色<select name="color" defaultValue={old?.color||'green'}><option value="green">松绿</option><option value="blue">雾蓝</option><option value="amber">麦黄</option></select></label></div>{old&&<div className="context-box"><h4>项目上下文</h4><p><Folder size={14}/>{data.resources.filter(r=>r.projectId===old.id).map(r=>r.name+' · '+r.device).join('；')||'还没有关联工程位置'}</p><p><Users size={14}/>{data.contacts.flatMap(c=>c.roles.filter(r=>r.projectId===old.id).map(r=>c.name+' · '+r.role)).join('；')||'还没有关联联系人'}</p><small>在「联系人」和「工程位置」中补充和维护。</small></div>}</>}
 {kind==='task'&&<>{projectField}<label>时间条内的简称<input name="shortName" maxLength={20} defaultValue={old?.shortName} placeholder="例如：首页设计，留空则使用名称"/></label><label>这件事的作用 / 具体内容<textarea name="description" defaultValue={old?.description} placeholder="为什么要做、做哪些内容、交付什么"/></label>{dateFields()}<div className="field-note">这里是预计推进跨度；超出项目日期时，会同步扩展项目周期。具体几点做，请添加日程。</div><div className="field-grid"><label>状态<select name="status" defaultValue={old?.status||'todo'}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>预计投入（小时）<input name="hours" type="number" min="0" max="10000" step="0.25" defaultValue={old?.hours??1}/></label></div><div className="field-grid"><label>负责人<input name="owner" defaultValue={old?.owner||'我'} maxLength={100}/></label><label>关联联系人<select name="contactId" defaultValue={old?.contactId||''}><option value="">无</option>{data.contacts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div><fieldset><legend>前置事项 · 可多选</legend><div className="dependency-list">{data.tasks.filter(t=>t.id!==item.id).map(t=><label className="check-row" key={t.id}><input type="checkbox" name="dependencies" value={t.id} defaultChecked={old?.dependencies?.includes(t.id)}/><span>{t.name}<small>{data.projects.find(p=>p.id===t.projectId)?.name}</small></span></label>)}{data.tasks.length<=1&&<span className="muted small">其他事项创建后，可以在这里关联前置条件。</span>}</div></fieldset><label>推进记录 / 完成成果<textarea name="result" defaultValue={old?.result} placeholder="记录已经推进了什么、卡在哪里、下一步是什么"/></label></>}
 {kind==='block'&&<><label>关联事项<select name="taskId" defaultValue={old?.taskId||item.taskId||''}><option value="">独立日程</option>{data.tasks.map(t=><option value={t.id} key={t.id}>{t.name} · {data.projects.find(p=>p.id===t.projectId)?.name}</option>)}</select></label>{dateFields(true)}<p className="field-note">使用北京时间（Asia/Shanghai）。重叠时段会在保存前提示。</p><label className="check-row"><input name="fixed" type="checkbox" defaultChecked={old?.fixed}/>固定安排（助理排程时应保留）</label><label className="check-row"><input name="done" type="checkbox" defaultChecked={old?.done}/>这段日程已经完成</label></>}
 {kind==='contact'&&<><label>微信 / 联系方式<input name="wechat" maxLength={150} defaultValue={old?.wechat} placeholder="记录微信号或方便识别的信息"/></label><label>协作备注<textarea name="notes" defaultValue={old?.notes} placeholder="这个人负责什么、沟通偏好、待跟进信息"/></label><fieldset><legend>参与哪些项目，各负责什么</legend>{data.projects.map(p=><div className="role-row" key={p.id}><label className="check-row"><input type="checkbox" name={'role-project-'+p.id} defaultChecked={old?.roles?.some((r:any)=>r.projectId===p.id)}/>{p.name}</label><input name={'role-'+p.id} maxLength={300} defaultValue={old?.roles?.find((r:any)=>r.projectId===p.id)?.role} placeholder="在这个项目中的角色 / 职责"/></div>)}{!data.projects.length&&<p className="muted">项目创建后可以在这里关联。</p>}</fieldset><p className="field-note">用于记录沟通上下文；不会自动向联系人发送消息。</p></>}
 {kind==='resource'&&<>{projectField}<label>在哪台电脑<Monitor size={14}/><input name="device" maxLength={160} defaultValue={old?.device} placeholder="例如：家里 MacBook / 公司 Windows 台式机"/></label><label>工程文件夹路径<input name="path" maxLength={2000} required defaultValue={old?.path} placeholder="例如：D:\Projects\brand-site"/></label><label>这个位置存放什么<textarea name="purpose" defaultValue={old?.purpose} placeholder="代码、文档、素材、运行说明…"/></label><p className="field-note">记录路径并可一键复制；浏览器不会直接访问电脑文件。</p></>}
 {error&&<p className="form-error"><AlertCircle size={15}/>{error}</p>}</div><div className="editor-footer">{old?<button type="button" className="danger-text" disabled={busy} onClick={remove}><Trash2 size={15}/>删除{title}</button>:<span/>}<div className="row"><button type="button" className="secondary" disabled={busy} onClick={close}>取消</button><button className="primary" disabled={busy}>{busy?'保存中…':'保存'+title}</button></div></div></form></div></>;
}
