'use client';
import {useConfirmation} from './confirmation';
import {useEffect,useRef,useState} from 'react';
import {X,Trash2,AlertCircle,Folder,Monitor,Users} from 'lucide-react';
import {addDays,localDay,statusLabels,type Data,type Operation} from '@/lib/domain';
import {captureBaseline,mergeChanges,records,fieldLabels,MergeValidationError,type Kind} from '@/lib/changes';
import {readDraft,writeDraft,clearDraft,draftKey,formEntries,restoreEntries,recordEntries,type EditorDraft} from '@/lib/editor-draft';
import {type SaveWorkspace,type ConflictDetails} from './use-workspace';
export type EditKind=Kind;
export type EditItem={kind:EditKind;id?:string;projectId?:string;taskId?:string;date?:string;status?:'todo'|'doing'|'waiting'|'done'|'paused'};
type Props={item:EditItem;data:Data;busy:boolean;close:()=>void;save:SaveWorkspace};
export default function Editor({item,data:liveData,busy,close,save}:Props){
 const {confirm,dialog}=useConfirmation(),data=liveData,{kind}=item;
 const key=useRef(draftKey({...item,date:item.id?undefined:item.date||localDay()})).current;
 const [initial]=useState(()=>{const saved=readDraft(key);if(saved)return saved;const id=item.id||crypto.randomUUID(),record=records(data,kind).find(v=>v.id===item.id)||null;return {version:1,kind,id,record,baseline:captureBaseline(data,[{type:(kind+'.save') as Operation['type'],data:{id}}]),deletionBaseline:record?captureBaseline(data,[{type:(kind+'.delete') as Operation['type'],id}]):{records:[],deletions:{}},entries:[]} as EditorDraft});
 const session=useRef(initial),old=session.current.record as any,title={project:'项目',task:'事项',block:'日程',contact:'联系人',resource:'工程位置'}[kind];
 const dirty=useRef(initial.entries.length>0),form=useRef<HTMLFormElement>(null),id=useRef(initial.id),submitting=useRef(false),[localBusy,setLocalBusy]=useState(false),[error,setError]=useState(''),[draftStatus,setDraftStatus]=useState(initial.entries.length?'已恢复未保存草稿':''),[conflict,setConflict]=useState<ConflictDetails|null>(null),[choices,setChoices]=useState<Record<string,string>>({});
 const pendingOps=useRef<Operation[]>([]),locked=busy||localBusy,today=item.date||localDay(),projectId=old?.projectId||item.projectId||data.projects[0]?.id||'';
 const [restore,setRestore]=useState<[string,string][]|null>(null);
 useEffect(()=>{if(restore&&form.current){restoreEntries(form.current,restore);setRestore(null)}},[restore,liveData]);
 function cache(){if(!form.current||locked)return false;if(!conflict)session.current.entries=formEntries(form.current);dirty.current=true;const ok=writeDraft(key,session.current);setDraftStatus(ok?'草稿已保存在此标签页':'草稿暂存失败，请先保存或复制内容');return ok;}
 async function requestClose(){if(locked)return;if(dirty.current){if(!cache())return;if(!await confirm('还有未保存的修改。关闭后会保留草稿，下次打开可继续编辑。'))return;}close();}
 async function discard(){if(locked||!await confirm('放弃这份未保存草稿？已经保存的内容不受影响。'))return;clearDraft(key);dirty.current=false;close();}
 useEffect(()=>{if(form.current&&initial.entries.length)restoreEntries(form.current,initial.entries);form.current?.querySelector<HTMLInputElement>('input')?.focus();},[]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty.current&&!writeDraft(key,session.current)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[key]);
 useEffect(()=>{function onKey(event:KeyboardEvent){if(event.key==='Escape'&&!locked)void requestClose();if(event.key==='Tab'&&form.current){const inputs=Array.from(form.current.querySelectorAll<HTMLElement>('input,button,select,textarea,a[href]')).filter(el=>!el.matches(':disabled'));if(event.shiftKey&&document.activeElement===inputs[0]){event.preventDefault();inputs.at(-1)?.focus()}else if(!event.shiftKey&&document.activeElement===inputs.at(-1)){event.preventDefault();inputs[0]?.focus()}}}document.addEventListener('keydown',onKey);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=previous}},[locked,close]);
 async function submit(event:React.FormEvent){
  event.preventDefault();if(locked||submitting.current||conflict)return;setError('');cache();
  const f=new FormData(form.current!),val=(s:string)=>String(f.get(s)||''),common={...old,id:id.current,name:val('name')};let value:any;
  if(kind==='project')value={...common,goal:val('goal'),start:val('start'),end:val('end'),status:val('status'),color:val('color')};
  if(kind==='task')value={...common,projectId:val('projectId'),shortName:val('shortName'),description:val('description'),start:val('start'),end:val('end'),status:val('status'),owner:val('owner'),hours:Number(val('hours')),contactId:val('contactId'),dependencies:f.getAll('dependencies').map(String),updatedAt:old?.updatedAt||'',result:val('result')};
  if(kind==='block')value={...common,taskId:val('taskId'),start:val('start'),end:val('end'),fixed:f.has('fixed'),done:f.has('done')};
  if(kind==='contact')value={...common,wechat:val('wechat'),notes:val('notes'),roles:data.projects.filter(p=>f.has('role-project-'+p.id)).map(p=>({projectId:p.id,role:val('role-'+p.id)}))};
  if(kind==='resource')value={...common,projectId:val('projectId'),device:val('device'),path:val('path'),purpose:val('purpose')};
  const operations:Operation[]=[{type:(kind+'.save') as Operation['type'],data:value}],fingerprint=JSON.stringify(operations);pendingOps.current=operations;
  if(session.current.attempt?.fingerprint!==fingerprint)session.current.attempt={fingerprint,id:crypto.randomUUID()};writeDraft(key,session.current);
  submitting.current=true;setLocalBusy(true);let conflicted=false;
  try{const ok=await save(operations,(old?'更新':'新增')+title+'：'+value.name,{baseline:session.current.baseline,operationId:session.current.attempt.id,onConflict:detail=>{conflicted=true;if(detail.code==='INVALID_MERGE'&&detail.operations){adoptMerged(detail.snapshot.data,detail.operations);setError('已载入合并后的内容，尚未保存：'+detail.message+' 请修改后重试。')}else{setConflict(detail);setChoices({});setError('')}}});if(ok){clearDraft(key);dirty.current=false;close()}else if(!conflicted)setError('尚未保存。输入和草稿仍保留，请检查提示后重试。');}finally{submitting.current=false;setLocalBusy(false)}
 }
 function adoptMerged(current:Data,ops:Operation[]){session.current.record=records(current,kind).find(v=>v.id===id.current)||null;session.current.baseline=captureBaseline(current,ops);session.current.deletionBaseline=captureBaseline(current,[{type:(kind+'.delete') as Operation['type'],id:id.current}]);session.current.entries=recordEntries(ops[0].data as any);session.current.attempt=undefined;setRestore(session.current.entries);writeDraft(key,session.current);setConflict(null);setChoices({});}
 function resolveConflict(){if(!conflict||!form.current)return;try{const ops=mergeChanges(conflict.snapshot.data,pendingOps.current,session.current.baseline,choices);adoptMerged(conflict.snapshot.data,ops);setError('已保留所选内容，请核对后再次保存。');}catch(err){if(err instanceof MergeValidationError)adoptMerged(conflict.snapshot.data,err.operations);setError(err instanceof Error?err.message:'请重新核对内容。');}}
 async function remove(){if(locked)return;setLocalBusy(true);try{if(await save([{type:(kind+'.delete') as Operation['type'],id:item.id}],'删除'+title+'：'+old.name,{baseline:session.current.deletionBaseline,onConflict:detail=>{session.current.deletionBaseline=captureBaseline(detail.snapshot.data,[{type:(kind+'.delete') as Operation['type'],id:item.id}]);writeDraft(key,session.current);setError('记录或关联内容已有更新，暂未删除。已载入最新删除范围，再次点击删除可重新核对后果；编辑草稿仍保留。')}})){clearDraft(key);dirty.current=false;close()}}finally{setLocalBusy(false)}}
 const dateFields=(withTime=false)=><div className="field-grid"><label>开始{withTime?'时间':'日期'}<input name="start" type={withTime?'datetime-local':'date'} required defaultValue={old?.start||(withTime?today+'T09:00':today)}/></label><label>结束{withTime?'时间':'日期'}<input name="end" type={withTime?'datetime-local':'date'} required defaultValue={old?.end||(withTime?today+'T10:00':addDays(today,kind==='project'?14:2))}/></label></div>;
 const projectField=<label>所属项目<select name="projectId" defaultValue={projectId} required><option value="" disabled>选择项目</option>{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>;
 return <>{dialog}<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!locked)requestClose()}}><form ref={form} className="editor" role="dialog" aria-modal="true" aria-labelledby="editor-title" onSubmit={submit} onInput={cache} onChange={cache}><div className="editor-header"><div><span className="eyebrow">让安排更清晰</span><h2 id="editor-title">{old?'编辑':'新建'}{title}</h2></div><button type="button" disabled={locked} className="icon-button" aria-label="关闭编辑" onClick={requestClose}><X/></button></div><div className="editor-body">{draftStatus&&<div className="draft-notice" role="status">{draftStatus}<button type="button" className="text-button" disabled={locked} onClick={discard}>放弃草稿</button></div>}<fieldset className="editor-fields" disabled={locked||!!conflict}><label>{title}名称<input name="name" required maxLength={160} defaultValue={old?.name|| (kind==='block'?data.tasks.find(t=>t.id===item.taskId)?.name:'')} placeholder={kind==='project'?'例如：品牌官网第一版':'写下清晰、具体的名称'}/></label>
 {kind==='project'&&<><label>这个项目要达成什么<textarea name="goal" defaultValue={old?.goal} placeholder="目标、交付物，以及完成的标准"/></label>{dateFields()}<div className="field-grid"><label>项目状态<select name="status" defaultValue={old?.status||'active'}><option value="active">推进中</option><option value="paused">暂停</option><option value="done">已完成</option></select></label><label>项目颜色<select name="color" defaultValue={old?.color||'green'}><option value="green">松绿</option><option value="blue">雾蓝</option><option value="amber">麦黄</option></select></label></div>{old&&<div className="context-box"><h4>项目上下文</h4><p><Folder size={14}/>{data.resources.filter(r=>r.projectId===old.id).map(r=>r.name+' · '+r.device).join('；')||'还没有关联工程位置'}</p><p><Users size={14}/>{data.contacts.flatMap(c=>c.roles.filter(r=>r.projectId===old.id).map(r=>c.name+' · '+r.role)).join('；')||'还没有关联联系人'}</p><small>在「联系人」和「工程位置」中补充和维护。</small></div>}</>}
 {kind==='task'&&<>{projectField}<label>时间条内的简称<input name="shortName" maxLength={20} defaultValue={old?.shortName} placeholder="例如：首页设计，留空则使用名称"/></label><label>这件事的作用 / 具体内容<textarea name="description" defaultValue={old?.description} placeholder="为什么要做、做哪些内容、交付什么"/></label>{dateFields()}<div className="field-note">这里是预计推进跨度；超出项目日期时，会同步扩展项目周期。具体几点做，请添加日程。</div><div className="field-grid"><label>状态<select name="status" defaultValue={old?.status||item.status||'todo'}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>预计投入（小时）<input name="hours" type="number" min="0" max="10000" step="0.25" defaultValue={old?.hours??1}/></label></div><div className="field-grid"><label>负责人<input name="owner" defaultValue={old?.owner||'我'} maxLength={100}/></label><label>关联联系人<select name="contactId" defaultValue={old?.contactId||''}><option value="">无</option>{data.contacts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div><fieldset><legend>前置事项 · 可多选</legend><div className="dependency-list">{data.tasks.filter(t=>t.id!==item.id).map(t=><label className="check-row" key={t.id}><input type="checkbox" name="dependencies" value={t.id} defaultChecked={old?.dependencies?.includes(t.id)}/><span>{t.name}<small>{data.projects.find(p=>p.id===t.projectId)?.name}</small></span></label>)}{data.tasks.length<=1&&<span className="muted small">其他事项创建后，可以在这里关联前置条件。</span>}</div></fieldset><label>推进记录 / 完成成果<textarea name="result" defaultValue={old?.result} placeholder="记录已经推进了什么、卡在哪里、下一步是什么"/></label></>}
 {kind==='block'&&<><label>关联事项<select name="taskId" defaultValue={old?.taskId||item.taskId||''}><option value="">独立日程</option>{data.tasks.map(t=><option value={t.id} key={t.id}>{t.name} · {data.projects.find(p=>p.id===t.projectId)?.name}</option>)}</select></label>{dateFields(true)}<p className="field-note">使用北京时间（Asia/Shanghai）。重叠时段会在保存前提示。</p><label className="check-row"><input name="fixed" type="checkbox" defaultChecked={old?.fixed}/>固定安排（助理排程时应保留）</label><label className="check-row"><input name="done" type="checkbox" defaultChecked={old?.done}/>这段日程已经完成</label></>}
 {kind==='contact'&&<><label>微信 / 联系方式<input name="wechat" maxLength={150} defaultValue={old?.wechat} placeholder="记录微信号或方便识别的信息"/></label><label>协作备注<textarea name="notes" defaultValue={old?.notes} placeholder="这个人负责什么、沟通偏好、待跟进信息"/></label><fieldset><legend>参与哪些项目，各负责什么</legend>{data.projects.map(p=><div className="role-row" key={p.id}><label className="check-row"><input type="checkbox" name={'role-project-'+p.id} defaultChecked={old?.roles?.some((r:any)=>r.projectId===p.id)}/>{p.name}</label><input name={'role-'+p.id} maxLength={300} defaultValue={old?.roles?.find((r:any)=>r.projectId===p.id)?.role} placeholder="在这个项目中的角色 / 职责"/></div>)}{!data.projects.length&&<p className="muted">项目创建后可以在这里关联。</p>}</fieldset><p className="field-note">用于记录沟通上下文；不会自动向联系人发送消息。</p></>}
 {kind==='resource'&&<>{projectField}<label>在哪台电脑<Monitor size={14}/><input name="device" maxLength={160} defaultValue={old?.device} placeholder="例如：家里 MacBook / 公司 Windows 台式机"/></label><label>工程文件夹路径<input name="path" maxLength={2000} required defaultValue={old?.path} placeholder="例如：D:\Projects\brand-site"/></label><label>这个位置存放什么<textarea name="purpose" defaultValue={old?.purpose} placeholder="代码、文档、素材、运行说明…"/></label><p className="field-note">记录路径并可一键复制；浏览器不会直接访问电脑文件。</p></>}
 </fieldset>{conflict&&<section className="field-conflicts" role="alert"><h3>选择要保留的内容</h3><p>只有下面这些内容被两边同时改动，其他字段会自动合并。</p>{conflict.conflicts.map(c=><div className="field-conflict" key={c.field}><strong>{fieldLabels[c.field]||c.field}</strong>{c.field.startsWith("$")?<p>记录已删除或关联内容已有变化。草稿仍保留，请关闭后核对最新记录。</p>:<><p>你填写的：{typeof c.proposed==="object"?JSON.stringify(c.proposed):String(c.proposed??"空")}</p><p>当前已保存：{typeof c.current==="object"?JSON.stringify(c.current):String(c.current??"空")}</p><label>保留哪份内容<select aria-label={"保留"+(fieldLabels[c.field]||c.field)} value={choices[c.field]||""} onChange={e=>setChoices(v=>({...v,[c.field]:e.target.value}))}><option value="" disabled>请选择</option><option value="mine">我填写的</option><option value="theirs">当前已保存的</option></select></label></>}</div>)}{!conflict.conflicts.some(c=>c.field.startsWith("$"))&&<button type="button" className="secondary" disabled={conflict.conflicts.some(c=>!choices[c.field])} onClick={resolveConflict}>采用所选内容</button>}</section>}{error&&<p className="form-error"><AlertCircle size={15}/>{error}</p>}</div><div className="editor-footer">{old?<button type="button" className="danger-text" disabled={locked} onClick={remove}><Trash2 size={15}/>删除{title}</button>:<span/>}<div className="row"><button type="button" className="secondary" disabled={locked} onClick={requestClose}>取消</button><button className="primary" disabled={locked||!!conflict}>{locked?'保存中…':'保存'+title}</button></div></div></form></div></>;
}
