'use client';
import {useState} from 'react';
import {Search,X,Plus,ArrowUpRight} from 'lucide-react';
import {type Data} from '@/lib/domain';
import {type EditItem} from './editor';
import RecoveryDialog from './recovery-dialog';
export default function FindAnything({data,open,project,close}:{data:Data;open:(v:EditItem)=>void;project:(id:string)=>void;close:()=>void}){
 const [query,setQuery]=useState(''),[limit,setLimit]=useState(40),q=query.trim().toLocaleLowerCase();
 const rows=[...data.projects.map(p=>({kind:'project' as const,id:p.id,name:p.name,detail:'项目 · '+p.goal})),...data.tasks.map(t=>({kind:'task' as const,id:t.id,name:t.name,detail:(data.projects.find(p=>p.id===t.projectId)?.name||'')+' · '+t.description+' '+t.result})),...data.contacts.map(c=>({kind:'contact' as const,id:c.id,name:c.name,detail:'联系人 · '+c.wechat+' '+c.notes+' '+c.roles.map(r=>(data.projects.find(p=>p.id===r.projectId)?.name||'')+' '+r.role).join(' ')})),...data.resources.map(r=>({kind:'resource' as const,id:r.id,name:r.name,detail:'文件 · '+r.device+' '+r.path+' '+r.purpose+' '+data.projects.find(p=>p.id===r.projectId)?.name})),...data.captures.map(c=>({kind:'capture' as const,id:c.id,name:c.name,detail:'随手记 · '+c.notes})),...data.followups.map(f=>({kind:'followup' as const,id:f.id,name:f.name,detail:'跟进 · '+f.dueAt.replace('T',' ')+' '+f.notes})),...data.blocks.map(b=>({kind:'block' as const,id:b.id,name:b.name,detail:'日程 · '+b.start.replace('T',' ')+'—'+b.end.slice(11)}))];
 const matches=rows.filter(r=>q?(r.name+' '+r.detail).toLocaleLowerCase().includes(q):r.kind==='contact'||r.kind==='resource'),visible=matches.slice(0,limit);
 return <RecoveryDialog label="找人、文件或事情" close={close}><div className="row between"><h2>找人、文件或事情</h2><button className="icon-button" aria-label="关闭查找" onClick={close}><X size={18}/></button></div><label className="global-search-input"><Search size={18}/><input autoFocus aria-label="搜索全部内容" placeholder="名字、项目、电脑、路径…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}}/></label><div className="search-results">{visible.map(r=><button className="search-result" key={r.kind+r.id} onClick={()=>{close();if(r.kind==='project')project(r.id);else open({kind:r.kind,id:r.id})}}><span><strong>{r.name}</strong><small>{r.detail}</small></span><ArrowUpRight size={16}/></button>)}{!visible.length&&<p className="quiet-empty">{q?'没有找到，换一个关键词试试。':'记下的人和文件会出现在这里，也可以搜索所有事情。'}</p>}{matches.length>limit&&<button className="text-button" onClick={()=>setLimit(v=>v+40)}>继续显示 · 还有 {matches.length-limit} 条</button>}</div><button className="text-button" onClick={()=>{close();open({kind:'contact'})}}><Plus size={15}/>记一位联系人</button></RecoveryDialog>;
}
