'use client';
import {useState,useEffect,useRef} from 'react';
import {ChevronLeft,ChevronRight,Plus,ChevronDown,Check,Clock,Link2} from 'lucide-react';
import {timelineCell,taskPosition} from '@/lib/planning';
import {addDays,daysBetween,localDay,statusLabels,type Data,type Task,type Project} from '@/lib/domain';
type Props={data:Data;editTask:(t:Task)=>void;editProject:(p:Project)=>void;addTask:(id:string)=>void;filter:string};
export default function Timeline({data,editTask,editProject,addTask,filter}:Props){
 const scroller=useRef<HTMLDivElement>(null);const [zoom,setZoom]=useState(112);const container=useRef<HTMLElement>(null);const [available,setAvailable]=useState(900);useEffect(()=>{const el=container.current;if(!el)return;const r=new ResizeObserver(()=>setAvailable(el.clientWidth));r.observe(el);return()=>r.disconnect()},[]);const today=localDay();const [mode,setMode]=useState('all'),[offset,setOffset]=useState(0),[collapsed,setCollapsed]=useState<string[]>([]);const [hover,setHover]=useState<{t:Task;x:number;y:number}|null>(null);
 const projects=data.projects.filter(p=>!filter||p.name.toLowerCase().includes(filter.toLowerCase())||data.tasks.some(t=>t.projectId===p.id&&t.name.toLowerCase().includes(filter.toLowerCase())));
 const dates=projects.flatMap(p=>[p.start,p.end]).concat(data.tasks.filter(t=>projects.some(p=>p.id===t.projectId)).flatMap(t=>[t.start,t.end])).sort();
 const start=mode==='all'&&dates.length?addDays(dates[0],-1):addDays(today,offset-2);const total=mode==='all'&&dates.length?Math.max(14,daysBetween(start,dates[dates.length-1])+3):mode==='month'?30:14;const cell=zoom===112?timelineCell(available,total):zoom;const width=total*cell;const tick=Math.max(1,Math.ceil(38/cell));
 const position=(t:Task)=>taskPosition(start,t,cell);
 function show(t:Task,el:HTMLElement){const r=el.getBoundingClientRect();setHover({t,x:Math.max(12,Math.min(r.left,window.innerWidth-338)),y:r.bottom+260>window.innerHeight?Math.max(12,r.top-250):r.bottom+8});}
 return <section ref={container} className="timeline-card"><div className="panel-toolbar"><div className="segmented">{[['all','项目全程'],['week','两周'],['month','月']].map(([v,l])=><button key={v} className={mode===v?'selected':''} onClick={()=>{setMode(v);setOffset(0)}}>{l}</button>)}</div><div className="row timeline-controls"><select aria-label="时间轴缩放" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={72}>紧凑</option><option value={112}>标准</option><option value={160}>舒展</option></select><span className="muted small">{start.replaceAll('-','.')} — {addDays(start,total-1).replaceAll('-','.')}</span>{mode==='all'&&<button className="text-button" onClick={()=>scroller.current?.scrollTo({left:Math.max(0,daysBetween(start,today)*cell-150),behavior:'smooth'})}>定位今天</button>}{mode!=='all'&&<><button className="icon-button" aria-label="上一段时间" onClick={()=>setOffset(o=>o-(mode==='month'?30:14))}><ChevronLeft size={16}/></button><button className="text-button" onClick={()=>setOffset(0)}>今天</button><button className="icon-button" aria-label="下一段时间" onClick={()=>setOffset(o=>o+(mode==='month'?30:14))}><ChevronRight size={16}/></button></>}</div></div>
 {mode==='all'&&projects.length>0&&<div className="project-map"><div className="overview-caption"><span>全程导航</span><small>点击事项，定位到下方时间轴</small></div>{projects.map(p=>{const tasks=data.tasks.filter(t=>t.projectId===p.id).sort((a,b)=>a.start.localeCompare(b.start)),ends:string[]=[];const items=tasks.map(t=>{let lane=ends.findIndex(e=>e<t.start);if(lane<0)lane=ends.length;ends[lane]=t.end;return {t,lane}});return <div className={'overview-row '+p.color} key={p.id}><span title={p.name}>{p.name}</span><div className="overview-lane" style={{height:Math.max(20,ends.length*17)}}>{items.map(({t,lane})=><button key={t.id} className={'overview-task '+t.status} style={{left:daysBetween(start,t.start)/total*100+'%',width:(daysBetween(t.start,t.end)+1)/total*100+'%',top:lane*17}} title={t.name+' · '+t.start+' → '+t.end} aria-label={'定位事项：'+t.name} onClick={()=>scroller.current?.scrollTo({left:Math.max(0,daysBetween(start,t.start)*cell-20),behavior:'smooth'})}>{t.shortName||t.name}</button>)}</div></div>})}</div>}
 <div ref={scroller} className="timeline-scroll" tabIndex={0} aria-label="项目时间轴，可横向滚动" onScroll={()=>setHover(null)}><div className="timeline-inner" style={{minWidth:`calc(${width}px + var(--project-column))`}}><div className="timeline-header"><div className="project-head">项目 / 推进情况</div><div className="date-track" style={{width}}>{Array.from({length:Math.ceil(total/tick)},(_,index)=>{const i=index*tick;const d=addDays(start,i);return <div key={d} className={'date-cell '+(d===today?'is-today':'')} style={{width:Math.min(tick,total-i)*cell}}><span>{d.slice(5).replace('-','/')}</span><small>{cell>40?['日','一','二','三','四','五','六'][new Date(d+'T12:00:00').getDay()]:''}</small></div>})}</div></div>
 {projects.map(p=>{const tasks=data.tasks.filter(t=>t.projectId===p.id).sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end));const lanes:string[]=[];const assigned=new Map<string,number>();tasks.forEach(t=>{let lane=lanes.findIndex(end=>end<t.start);if(lane<0)lane=lanes.length;lanes[lane]=t.end;assigned.set(t.id,lane)});const closed=collapsed.includes(p.id),height=closed?46:Math.max(100,lanes.length*48+28);const done=tasks.filter(t=>t.status==='done').length;const active=tasks.filter(t=>t.status==='doing').length;return <div className={'project-lane '+p.color} key={p.id}><div className="project-label" style={{minHeight:height}}><div className="row"><button className={'collapse-button '+(closed?'closed':'')} aria-label={closed?'展开项目':'收起项目'} onClick={()=>setCollapsed(a=>closed?a.filter(id=>id!==p.id):[...a,p.id])}><ChevronDown size={14}/></button><button className="project-name" onClick={()=>editProject(p)}>{p.name}</button></div>{!closed&&<><div className="project-meta">{done}/{tasks.length} 已完成 <span>· {active} 进行中</span></div><div className="progress-track"><i style={{width:`${tasks.length?done/tasks.length*100:0}%`}}/></div><button className="subtle-add" onClick={()=>addTask(p.id)}><Plus size={12}/> 添加事项</button></>}</div><div className="bars-track" style={{width,height,backgroundSize:`${cell}px 100%`}}>
 {daysBetween(start,today)>=0&&daysBetween(start,today)<total&&<div className="today-line" style={{left:daysBetween(start,today)*cell+cell/2}}/>}
 {!closed&&<><svg className="dependencies" width={width} height={height} aria-hidden="true"><defs><marker id={'arrow-'+p.id} markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5" fill="none" stroke="#9eaaa1"/></marker></defs>{tasks.flatMap(t=>t.dependencies.map(id=>{const prev=tasks.find(x=>x.id===id);if(!prev)return null;const from=position(prev),to=position(t),y1=assigned.get(id)!*48+32,y2=assigned.get(t.id)!*48+32;return <path key={id+t.id} d={`M ${from.left+from.width} ${y1} C ${from.left+from.width+16} ${y1}, ${to.left-16} ${y2}, ${to.left-3} ${y2}`} stroke="#9eaaa1" strokeWidth="1" fill="none" markerEnd={`url(#arrow-${p.id})`}/>}))}</svg>
 {tasks.map(t=>{const pos=position(t);return <button key={t.id} className={'task-bar '+t.status} style={{left:pos.left,width:pos.width,top:assigned.get(t.id)!*48+14}} onClick={()=>{setHover(null);editTask(t)}} onMouseEnter={e=>show(t,e.currentTarget)} onMouseLeave={()=>setHover(null)} onFocus={e=>show(t,e.currentTarget)} onBlur={()=>setHover(null)} aria-label={`${t.name}，${t.start} 至 ${t.end}，${statusLabels[t.status]}，点击编辑`}>{pos.width>100&&<span className="bar-dot">{t.status==='done'?<Check size={12}/>:null}</span>}<strong>{t.shortName||t.name}</strong>{pos.width>130&&<small>{daysBetween(t.start,t.end)+1} 天</small>}</button>})}{!tasks.length&&<button className="empty-lane" onClick={()=>addTask(p.id)}>＋ 在这个项目中安排第一件事</button>}</>}
 {closed&&<div className="collapsed-summary">{tasks.length} 件事 · {done} 已完成</div>}</div></div>})}
 </div></div><div className="timeline-footer"><span>横向滚动查看全程 · 条长表示预计跨度 · 上下排列表示并行</span><div className="legend"><span><i className="green-dot"/>进行中</span><span><i className="amber-dot"/>等待</span><span><i className="gray-dot"/>待开始</span><span>✓ 已完成</span></div></div>
 {hover&&<div role="tooltip" className="task-tooltip" style={{left:hover.x,top:hover.y}}><div className="row between"><span className={'status-badge '+hover.t.status}>{statusLabels[hover.t.status]}</span><small className="muted">点击查看 / 编辑</small></div><h3>{hover.t.name}</h3><p>{hover.t.description||'还没有补充事项说明。'}</p><div className="tooltip-line"><Clock size={14}/>{hover.t.start} → {hover.t.end} · 预计投入 {hover.t.hours} 小时</div><div className="tooltip-line">负责人：{hover.t.owner||'未指定'}</div>{hover.t.dependencies.length>0&&<div className="tooltip-line"><Link2 size={14}/>前置：{hover.t.dependencies.map(id=>data.tasks.find(t=>t.id===id)?.name).join('、')}</div>}{hover.t.contactId&&<div className="tooltip-line">联系：{data.contacts.find(c=>c.id===hover.t.contactId)?.name}</div>}</div>}
 </section>;
}
