'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {LayoutGrid,CalendarDays,Workflow,Users,FolderOpen,Plus,Search,AudioLines,ArrowUpRight,RefreshCw,Download,Copy,Monitor,Clock,Leaf,Menu,X,AlertCircle,CheckCircle2} from 'lucide-react';
import {localDay,statusLabels,emptyData,type Snapshot,type Operation} from '@/lib/domain';
import {demoOperations} from '@/lib/demo';
import Timeline from './timeline';
import Editor,{type EditItem} from './editor';
import Assistant from './assistant';
import CalendarView from './calendar';
import {useWorkspaceTools} from './webmcp';
const nav=[{id:'projects',label:'项目全景',icon:LayoutGrid},{id:'today',label:'我的日程',icon:CalendarDays},{id:'flow',label:'推进看板',icon:Workflow},{id:'contacts',label:'联系人',icon:Users},{id:'resources',label:'工程位置',icon:FolderOpen}] as const;
type View=typeof nav[number]['id'];
async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'服务暂不可用，请重试。');return j;}
export default function Workspace(){
 const [snapshot,setSnapshot]=useState<Snapshot>({data:emptyData(),revision:0}),[loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{text:string;error?:boolean}|null>(null),[view,setView]=useState<View>('projects'),[filter,setFilter]=useState(''),[agentOpen,setAgentOpen]=useState(true),[mobileNav,setMobileNav]=useState(false),[editor,setEditor]=useState<(EditItem&{revision:number})|null>(null),[date,setDate]=useState(localDay()),[flowProject,setFlowProject]=useState('');
 const saving=useRef(false),latest=useRef(snapshot),noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const data=snapshot.data,today=localDay();
 const notify=useCallback((text:string,error=false)=>{if(noticeTimer.current)clearTimeout(noticeTimer.current);setNotice({text,error});if(!error)noticeTimer.current=setTimeout(()=>setNotice(null),4500)},[]);
 const receive=useCallback((s:Snapshot)=>{if(s.revision>=latest.current.revision){latest.current=s;setSnapshot(s)}},[]);
 const reload=useCallback(async()=>{setLoading(true);try{const s=await request('/api/workspace');receive(s);setLoaded(true);setNotice(null)}catch(e){notify(e instanceof Error?e.message:'读取失败',true)}finally{setLoading(false)}},[receive,notify]);
 useEffect(()=>{void reload();if(window.innerWidth<1200)setAgentOpen(false);return()=>{if(noticeTimer.current)clearTimeout(noticeTimer.current)}},[reload]);
 const save=useCallback(async(operations:Operation[],summary:string,revision?:number,operationId?:string)=>{if(saving.current)return false;saving.current=true;setBusy(true);try{const s=await request('/api/workspace',{revision:revision??latest.current.revision,operations,operationId:operationId||crypto.randomUUID(),summary});receive(s);notify(summary+'，已保存');return true}catch(e){notify(e instanceof Error?e.message:'保存失败',true);return false}finally{saving.current=false;setBusy(false)}},[receive,notify]);
 const closeEditor=useCallback(()=>setEditor(null),[]);
 const open=(item:EditItem)=>{if(!loaded)return;if((item.kind==='task'||item.kind==='resource')&&!data.projects.length){notify('先创建一个项目，再添加事项或工程位置。');setEditor({kind:'project',revision:snapshot.revision});return}setEditor({...item,revision:snapshot.revision})};
 useWorkspaceTools(snapshot,open);
 const changeView=(id:View)=>{setView(id);setFilter('');setMobileNav(false)};
 async function demo(){if(data.projects.length){notify('示例仅可加入空工作空间。',true);return}await save(demoOperations(),'载入示例项目，可随时编辑或删除');}
 function backup(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),timezone:'Asia/Shanghai',data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='时间管理大师-'+today+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);notify('已复制到剪贴板')}catch{notify('复制失败，请手动选中并复制。',true)}}
 const active=data.projects.filter(p=>p.status==='active').length,doing=data.tasks.filter(t=>t.status==='doing').length,waiting=data.tasks.filter(t=>t.status==='waiting').length,done=data.tasks.filter(t=>t.status==='done').length;
 const matching=(s:string)=>s.toLowerCase().includes(filter.toLowerCase());
 const heading={projects:['项目全景','把每个项目的节奏，放在同一张时间地图上。'],today:['我的日程','给重要的事留出时间，也给自己留一点余地。'],flow:['推进看板','看见已经完成的，也看清下一步该往哪里走。'],contacts:['联系人','记住每个人在项目里的角色，让沟通接得上。'],resources:['工程位置','哪个项目，哪台电脑，哪个文件夹。都能找到。']}[view];
 const newItem:EditItem={kind:view==='projects'?'project':view==='today'?'block':view==='flow'?'task':view==='contacts'?'contact':'resource',date};
 return <div className={'app-shell '+(agentOpen?'with-agent':'')}><aside className={'sidebar '+(mobileNav?'mobile-open':'')}><a href="#" className="brand" onClick={e=>{e.preventDefault();changeView('projects')}}><span className="brand-mark"><Leaf size={23}/></span><span>时间管理大师<small>MAKE ROOM FOR WHAT MATTERS</small></span></a><div className="workspace-label"><span className="avatar">我</span><div><strong>我的工作空间</strong><small>安静地，把事情做好</small></div><button className="mobile-only icon-button" aria-label="关闭导航" onClick={()=>setMobileNav(false)}><X size={16}/></button></div><span className="nav-label">工作台</span><nav>{nav.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>changeView(n.id)}><n.icon size={18}/>{n.label}{n.id==='projects'&&data.projects.length>0&&<span>{data.projects.length}</span>}</button>)}</nav><div className="sidebar-note"><div className="tiny-orbit"/><p>有条理地前进，<br/>也可以从容一点。</p><small>{new Date(today+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</small></div><div className="sidebar-bottom"><button onClick={backup} disabled={!loaded} title="导出工作空间备份"><Download size={16}/>导出数据</button><span><i className="online-dot"/>{busy?'正在保存':loaded?'数据已同步':'等待连接'}</span></div></aside>
 <div className="main-shell"><header className="topbar"><div className="row"><button className="mobile-only icon-button" onClick={()=>setMobileNav(true)} aria-label="打开导航"><Menu size={20}/></button><span className="breadcrumb">工作台 <span>/</span> <strong>{heading[0]}</strong></span></div><div className="top-actions"><button className="icon-button" aria-label="刷新数据" disabled={loading||busy} onClick={reload}><RefreshCw size={16} className={loading?'spin':''}/></button><span className="timezone">北京时间</span><button className={'agent-toggle '+(agentOpen?'active':'')} onClick={()=>setAgentOpen(v=>!v)}><AudioLines size={17}/><span>时间伙伴</span></button></div></header>
 <main><div className="page-heading"><div><div className="eyebrow">{view==='projects'?'A LITTLE CLARITY, EVERY DAY':'YOUR PERSONAL WORKSPACE'}</div><h1>{heading[0]}<span className="heading-dot">.</span></h1><p>{heading[1]}</p></div><button className="primary" disabled={!loaded||busy} onClick={()=>open(newItem)}><Plus size={17}/>{view==='projects'?'新建项目':view==='today'?'添加日程':view==='flow'?'添加事项':view==='contacts'?'添加联系人':'添加位置'}</button></div>
 {notice&&<div className={'notice '+(notice.error?'error':'')} role={notice.error?'alert':'status'}>{notice.error?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>}<span>{notice.text}</span><button className="icon-button" onClick={()=>setNotice(null)} aria-label="关闭提示"><X size={15}/></button></div>}
 {!loaded?<div className="loading-state"><Leaf size={30}/><h3>{loading?'正在打开你的工作空间…':'工作空间暂时无法连接'}</h3><p>{loading?'项目和日程正在路上。':'点击右上方刷新，重新读取已保存的数据。'}</p></div>:<>
 {(view==='projects'||view==='flow')&&<div className="stats"><div><span>推进中的项目</span><strong>{String(active).padStart(2,'0')}<small>个项目</small></strong></div><div><span><i className="green-dot"/>正在推进</span><strong>{String(doing).padStart(2,'0')}<small>件事</small></strong></div><div><span><i className="amber-dot"/>等待跟进</span><strong>{String(waiting).padStart(2,'0')}<small>件事</small></strong></div><div><span>已经完成</span><strong>{String(done).padStart(2,'0')}<small>/ {data.tasks.length} 件事</small></strong></div></div>}
 {view!=='today'&&<div className="section-title"><div><h2>{view==='projects'?'所有项目的推进节奏':view==='flow'?'把下一步变得具体':view==='contacts'?'一起把事情做好的人':'项目与工作环境'}</h2><span>{view==='projects'?'同一条时间轴，自由并行':view==='flow'?'拖动卡片更新状态 · 点击查看详情':view==='contacts'?`${data.contacts.length} 位联系人`:`${data.resources.length} 个工程位置`}</span></div><div className="row">{view==='flow'&&<select className="filter-select" aria-label="筛选项目" value={flowProject} onChange={e=>setFlowProject(e.target.value)}><option value="">全部项目</option>{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>}<label className="search-box"><Search size={15}/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="搜索…" aria-label="搜索当前视图"/></label></div></div>}
 {view==='projects'&&(data.projects.length?<><Timeline data={data} editTask={t=>open({kind:'task',id:t.id})} editProject={p=>open({kind:'project',id:p.id})} addTask={id=>open({kind:'task',projectId:id})} filter={filter}/><div className="below-timeline"><div className="gentle-note"><span className="note-icon"><Leaf size={18}/></span><div><strong>每一步，都有它自己的节奏。</strong><p>点击项目管理目标；点击时间条，补充进展、依赖和成果。</p></div></div><button className="text-button" onClick={()=>changeView('flow')}>看接下来做什么 <ArrowUpRight size={15}/></button></div></>:<div className="empty-state"><div className="empty-illustration"><div/><div/><div/></div><h2>从一个项目开始，理清手上的事。</h2><p>把目标拆成可推进的事项，在时间轴上看见它们如何并行。</p><div className="row"><button className="primary" onClick={()=>open({kind:'project'})}><Plus size={16}/>创建第一个项目</button><button className="secondary" disabled={busy} onClick={demo}>先看看示例</button></div><small>示例包含并行事项、联系人和工程路径，可编辑或删除。</small></div>)}
 {view==='today'&&<CalendarView data={data} date={date} setDate={setDate} busy={busy} open={open} save={save}/>}
 {view==='flow'&&<div className="kanban">{Object.entries(statusLabels).map(([status,label])=>{const tasks=data.tasks.filter(t=>t.status===status&&(!flowProject||t.projectId===flowProject)&&matching(t.name));return <section className={'kanban-column '+status} key={status} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain'),t=data.tasks.find(t=>t.id===id);if(t&&t.status!==status&&!busy)void save([{type:'task.save',data:{...t,status}}],`${t.name}：${label}`)}}><div className="column-heading"><strong><i/>{label}</strong><span>{tasks.length}</span></div>{tasks.map(t=><button key={t.id} className="task-card" draggable={!busy} onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)} onClick={()=>open({kind:'task',id:t.id})}><small className={'project-tag '+data.projects.find(p=>p.id===t.projectId)?.color}>{data.projects.find(p=>p.id===t.projectId)?.name}</small><h3>{t.name}</h3><p>{t.result||t.description||'补充事项内容，让下一步更清晰。'}</p>{t.dependencies.some(id=>data.tasks.find(t=>t.id===id)?.status!=='done')&&<span className="dependency-warning">有前置事项未完成</span>}<footer><span><Clock size={12}/>{t.end.slice(5).replace('-','/')}</span><span>{t.owner||'未指定'}</span></footer></button>)}{!tasks.length&&<div className="kanban-empty">{filter?'没有匹配的事项':'暂时没有事项'}</div>}<button className="column-add" onClick={()=>open({kind:'task',projectId:flowProject})}><Plus size={14}/>添加事项</button></section>})}</div>}
 {view==='contacts'&&<div className="record-grid">{data.contacts.filter(c=>matching(c.name+' '+c.wechat+' '+c.notes)).map(c=><article className="contact-card" key={c.id}><div className="row between"><div className="row"><span className="contact-avatar">{c.name.slice(0,1)}</span><div><h3>{c.name}</h3><small>{c.wechat||'未记录联系方式'}</small></div></div><button className="text-button" onClick={()=>open({kind:'contact',id:c.id})}>编辑 <ArrowUpRight size={13}/></button></div><p>{c.notes||'还没有协作备注'}</p><div className="contact-roles">{c.roles.map((r,i)=><div key={i}><span>{data.projects.find(p=>p.id===r.projectId)?.name}</span><strong>{r.role||'角色待补充'}</strong></div>)}</div>{c.wechat&&<button className="subtle-add" onClick={()=>copy(c.wechat)}><Copy size={13}/>复制联系方式</button>}</article>)}{!data.contacts.filter(c=>matching(c.name+' '+c.wechat+' '+c.notes)).length&&<SmallEmpty title={filter?'没有匹配的联系人':'把项目里重要的人记下来'} text="同一个人可以参与不同项目，每个项目有各自的角色。" onClick={()=>open({kind:'contact'})}/>}</div>}
 {view==='resources'&&<div className="record-grid">{data.resources.filter(r=>matching(r.name+' '+r.device+' '+r.path)).map(r=><article className="resource-card" key={r.id}><div className="row between"><div className="folder-symbol"><FolderOpen size={24}/></div><button className="text-button" onClick={()=>open({kind:'resource',id:r.id})}>编辑 <ArrowUpRight size={13}/></button></div><small className="resource-project">{data.projects.find(p=>p.id===r.projectId)?.name}</small><h3>{r.name}</h3><div className="device-line"><Monitor size={14}/>{r.device||'设备待补充'}</div><div className="path-box"><code>{r.path}</code><button className="icon-button" aria-label={'复制'+r.name+'路径'} onClick={()=>copy(r.path)}><Copy size={15}/></button></div><p>{r.purpose||'还没有说明这个目录的用途。'}</p></article>)}{!data.resources.filter(r=>matching(r.name+' '+r.device+' '+r.path)).length&&<SmallEmpty title={filter?'没有匹配的工程':'下次开始时，知道从哪里打开'} text="记录工程所在电脑、文件夹路径和用途。" onClick={()=>open({kind:'resource'})}/>}</div>}
 {data.history.length>0&&view==='projects'&&<div className="recent-updates"><span>最近推进</span>{data.history.slice(-3).reverse().map((h,i)=><div key={i}><i/>{h.summary}<small>{new Date(h.at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div>)}</div>}
 </>}</main><footer className="app-footer"><span>时间管理大师</span><span>把时间留给值得的事。</span></footer></div>
 {agentOpen&&loaded&&<Assistant snapshot={snapshot} receive={receive} save={save} globalBusy={busy} close={()=>setAgentOpen(false)}/>}
 {editor&&<Editor key={editor.kind+(editor.id||'new')} item={editor} data={data} busy={busy} close={closeEditor} save={(ops,summary)=>save(ops,summary,editor.revision)}/>}
 </div>;
}
function SmallEmpty({title,text,onClick}:{title:string;text:string;onClick:()=>void}){return <div className="small-empty"><FolderOpen size={30}/><h3>{title}</h3><p>{text}</p><button className="secondary" onClick={onClick}><Plus size={15}/>添加记录</button></div>}
